export const protocolPaperMeta = {
  version: "1.0",
  date: "September 2026",
  title: "SolHandle Protocol Paper",
  subtitle: "NFT-Native Wallet Identity on Solana",
  tagline: "Your @ on Solana.",
};

export const protocolSections = [
  { number: "01", id: "purpose", title: "Purpose and problem", paragraphs: ["Solana addresses are secure identifiers, but they are difficult for people to recognize, remember and verify in everyday products. SolHandle adds a human-readable identity layer without replacing the underlying wallet address.", "A SolHandle is not a username stored in a private application database. It is a unique on-chain identity asset whose current wallet ownership can be independently verified through Solana."], callout: "Design objective: readable identity with cryptographic ownership, open verification and no custodial intermediary." },
  { number: "02", id: "ownership", title: "NFT-native ownership", paragraphs: ["Each claimed handle is represented by a Metaplex Core asset in the official SolHandle collection. The asset is minted directly to the claimant’s wallet. SolHandle does not custody the NFT, private key or seed phrase.", "The wallet that currently owns the verified asset controls the identity. There are no SolHandle renewal fees: after minting, continued ownership is determined by possession of the asset."], bullets: ["Official collection membership identifies authentic SolHandle assets.", "Deterministic protocol addresses enforce one canonical asset per handle.", "Ownership remains portable across compatible wallets and marketplaces."] },
  { number: "03", id: "resolution", title: "Forward and reverse resolution", paragraphs: ["Forward resolution maps @handle to the current verified owner of its official Core asset. Resolution verifies the program-owned HandleRecord, deterministic asset address, protocol configuration, Metaplex Core ownership and official collection.", "Reverse resolution maps a wallet to its Primary @handle. A reverse result is returned only when the wallet selected that handle as Primary and still owns the matching official asset."], facts: [["Forward", "@handle → current verified wallet"], ["Reverse", "wallet → verified Primary @handle"], ["Example", "@ansem → owner address"]] },
  { number: "04", id: "transfers", title: "Transfers and source of truth", paragraphs: ["Transferring the Core asset changes the handle’s owner without a separate SolHandle account migration. Resolvers read the asset’s current owner, so ownership follows the NFT.", "A previous owner’s Primary Handle becomes invalid when ownership no longer matches. The recipient may explicitly set the received handle as their own Primary Handle."], callout: "Authority order: Solana blockchain → indexer → database/cache → interface. The index improves speed; it cannot override chain state." },
  { number: "05", id: "minting", title: "Minting, pricing and rarity", paragraphs: ["Minting is one atomic Solana transaction: the program validates the canonical name, uniqueness, restrictions, accepted price and protocol state; transfers the fee; and creates the official collection asset directly in the claimant’s wallet.", "Rarity follows handle length. The current Mainnet schedule is stored in protocol configuration and is revalidated when a mint transaction is prepared."], facts: [["Legendary", "1 character · 3 SOL"], ["Ultra Rare", "2 characters · 2 SOL"], ["Rare", "3 characters · 1 SOL"], ["Uncommon", "4 characters · 0.5 SOL"], ["Standard", "5–20 characters · 0.1 SOL"]], callout: "The curated pool contains 2,500 Premium handles. A Premium handle adds a fixed 1 SOL surcharge to its length-based price." },
  { number: "06", id: "protected", title: "Reserved and protected names", paragraphs: ["Protocol terms, strategic names and recognizable organizations may be restricted on-chain to reduce impersonation. A reservation is a policy control, not an NFT and not ownership by SolHandle.", "Official claims require domain, wallet and, where necessary, known-channel verification. An approved identity is minted directly to the organization’s specified wallet."], bullets: ["Public minting is blocked while an active restriction applies.", "Official claims follow a separate verification path.", "Claimed official assets remain subject to the same on-chain ownership model."] },
  { number: "07", id: "architecture", title: "Protocol architecture", paragraphs: ["Protocol V2 runs on Solana Mainnet Beta. Program-derived addresses make configuration, handle records, assets, Primary Handles, restrictions and price overrides deterministic and independently reproducible.", "The Base44 service layer indexes confirmed state and exposes discovery and convenience APIs. Integrations requiring authoritative results should resolve directly from Solana through the SDK."], facts: [["Network", "Solana Mainnet Beta"], ["Program ID", "B7xiwfxGcR2Xz7tcUKrkB8Ly6NV8jU7LH1m6GJZRUuf"], ["Collection ID", "7XZzcbeFBxQA63n9avz44vnbpv34hDGYyHfCDmTdPBJP"], ["Protocol version", "2"]] },
  { number: "08", id: "integration", title: "SDK, API and integration", paragraphs: ["The public solhandle-sdk package provides normalization, deterministic address derivation, availability checks, forward resolution, reverse resolution, ownership verification and Primary Handle instruction construction.", "Wallets, dApps, explorers and payment products can accept an @handle as input, resolve it, show the resulting base58 address and require explicit user approval before continuing."], bullets: ["Install: npm install solhandle-sdk @solana/web3.js", "Use a production-grade Mainnet RPC connection.", "Treat REST resolver responses as a convenience layer, not as a substitute for chain verification.", "For native SOL, require safeForNativeSol before preparing payment."], links: [{ label: "Developer Center", href: "/developers" }, { label: "npm package", href: "https://www.npmjs.com/package/solhandle-sdk" }] },
  { number: "09", id: "security", title: "Security and non-custodial design", paragraphs: ["SolHandle never needs a user’s private key or seed phrase and does not hold user funds or assets. Transactions are assembled for wallet review and signed by the user.", "Resolvers reject mismatched deterministic records, unsupported protocol versions, non-Core assets and assets outside the official collection. Native-SOL integrations must additionally reject PDAs and program-owned accounts as payment destinations."], bullets: ["Verify network, program, collection, owner and destination before action.", "Display the resolved address and transaction details before signing.", "Mainnet transactions use real SOL and cannot be reversed by SolHandle.", "Protocol controls reduce risk but do not replace independent integration review and audit."] },
  { number: "10", id: "marketplaces", title: "Secondary markets and royalties", paragraphs: ["A handle may be transferred directly or listed on a compatible external marketplace. Marketplace discovery, settlement and custody remain external; SolHandle does not operate an internal escrow or exchange.", "The official collection is configured with a 5% secondary-market royalty. Royalty enforcement and settlement depend on the marketplace’s support for the Metaplex Core collection configuration."], callout: "A marketplace listing is not ownership. The current verified Core asset owner on Solana remains authoritative." },
  { number: "11", id: "roadmap", title: "Roadmap to wallet identity", paragraphs: ["The protocol, Mainnet deployment, protected-name flow, indexer, forward and reverse resolution, and public SDK form the current foundation.", "The next phase focuses on independent security readiness, production launch controls and verified adoption by wallets, explorers, payment tools and ecosystem applications."], bullets: ["Complete final security review and audit readiness.", "Verify partner implementations against the Mainnet integration test suite.", "Expand native resolution and Primary Handle display across the Solana ecosystem.", "Keep direct chain verification available as integrations scale."] },
  { number: "12", id: "verification", title: "Official links and verification", paragraphs: ["Partners and users should verify identifiers against the official documentation and inspect deployment accounts directly on Solana Explorer. Similar names, unofficial collections or cached marketplace labels are not sufficient proof of authenticity."], links: [{ label: "Official website", href: "https://solhandle.io/" }, { label: "Documentation", href: "/docs" }, { label: "Program on Solana Explorer", href: "https://explorer.solana.com/address/B7xiwfxGcR2Xz7tcUKrkB8Ly6NV8jU7LH1m6GJZRUuf" }, { label: "Collection on Solana Explorer", href: "https://explorer.solana.com/address/7XZzcbeFBxQA63n9avz44vnbpv34hDGYyHfCDmTdPBJP" }, { label: "Official X account", href: "https://x.com/Solhandle" }] },
];