import { Link } from 'react-router-dom';
import Header from '@/components/solhandle/Header';
import NamesControls from '@/components/solhandle/names/NamesControls';
import NamesResults from '@/components/solhandle/names/NamesResults';
import NamesWatchGate from '@/components/solhandle/names/NamesWatchGate';
import useNamesExplorer from '@/components/solhandle/names/useNamesExplorer';
export default function NamesExplorer() {
  const state = useNamesExplorer();
  return <main className="dark min-h-screen bg-background text-foreground"><div className="mx-auto min-h-screen max-w-7xl border-x border-border"><Header/><section className="px-5 py-5 sm:py-12 md:px-9"><div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="hidden text-sm font-medium tracking-wider text-names-accent sm:block">SOLHANDLE NAMES</p><h1 className="font-heading text-2xl font-semibold sm:mt-2 sm:text-4xl"><span className="sm:hidden">Names</span><span className="hidden sm:inline">Discover a name worth owning.</span></h1><p className="mt-1 text-xs text-muted-foreground sm:hidden">Find, follow and explore @handles.</p><p className="mt-3 hidden max-w-xl text-muted-foreground sm:block">Explore free and owned handles, follow your favorites, and inspect real interest before you mint or make an offer.</p></div></div><NamesControls {...state}/>{state.tab === 'watchlist' && !state.authorization ? <NamesWatchGate wallet={state.wallet} busy={state.busy} error={state.authError} onVerify={state.verify}/> : <NamesResults state={state}/>}<div className="mt-5 flex flex-wrap gap-4 text-xs sm:hidden"><Link to="/directory" className="text-names-secondary">Premium Directory</Link><Link to="/market" className="text-names-accent">Buy / sell in Marketplace →</Link></div></section></div></main>;
}