import { Link } from 'react-router-dom';
import { LoaderCircle } from 'lucide-react';
import NameCard from '@/components/solhandle/names/NameCard';
import NamesPagination from '@/components/solhandle/NamesPagination';
export default function NamesResults({ state }) {
  const { isLoading, isFetching, error, items, tab, rank, page, hasNext, onPrevious, onNext, refetch } = state;
  const suggested = items.some(item => item.suggested);
  if (isLoading) return <p className="mt-8 flex items-center gap-2 rounded-2xl border border-border bg-card p-8 text-muted-foreground"><LoaderCircle className="h-5 w-5 animate-spin"/>Loading names and checking live availability…</p>;
  if (error) return <div className="mt-8 rounded-2xl border border-border bg-card p-8"><p role="alert" className="text-destructive">{error.response?.data?.error || 'Names are temporarily unavailable.'}</p><button onClick={() => refetch()} className="mt-4 text-sm text-names-accent">Try again</button></div>;
  return <>{!items.length ? <section className="mt-8 rounded-2xl border border-border bg-card p-8 text-center"><h2 className="text-lg font-semibold">{tab === 'watchlist' ? 'No followed names here yet' : 'No names match this view yet'}</h2><p className="mt-3 text-sm text-muted-foreground">{tab === 'watchlist' ? 'Open a name and select Watch to add it to your private list.' : tab === 'for-sale' ? 'No active listings match your search. Try another name.' : rank === 'watched' && ['trending', 'available'].includes(tab) ? 'No watched names match this view yet. Only real watchlist activity is shown; suggested names are excluded.' : 'Search rankings are rebuilding from user-typed searches only. Automatic suggestions and historical unlabelled searches are excluded.'}</p><Link to="/" className="mt-5 inline-block text-sm text-names-accent">Search any @handle →</Link></section> : <><div className="mt-4 flex items-center justify-between gap-2 text-[11px] text-muted-foreground sm:mt-7 sm:text-xs"><span>{suggested ? 'Curated suggestions · live on-chain availability' : ['trending', 'available'].includes(tab) ? `Top names by ${rank === 'watched' ? 'watching wallets' : 'unique search sessions over 30 days'}` : 'Live on-chain status · inspect a name for details'}</span>{isFetching && <LoaderCircle className="h-4 w-4 animate-spin"/>}</div>{suggested && <p className="mt-2 rounded-xl border border-names-secondary/20 bg-names-secondary/5 p-3 text-xs text-muted-foreground sm:mt-3 sm:p-4 sm:text-sm">A hand-picked starter list of short words and memorable numbers, not a popularity ranking or proof of demand. Real activity replaces these suggestions automatically.</p>}<div className="mt-4 grid grid-cols-2 gap-2 sm:gap-4 lg:grid-cols-3 xl:grid-cols-4">{items.map(item => <NameCard key={item.handle} item={item}/>)}</div></>}
    <NamesPagination page={page} hasNext={hasNext} busy={isFetching} onPrevious={onPrevious} onNext={onNext}/>
    <details className="mt-4 rounded-xl border border-border p-3 sm:hidden"><summary className="cursor-pointer text-xs text-names-secondary">How rankings work</summary><p className="mt-3 text-xs leading-relaxed text-muted-foreground">Only user-typed searches count; automatic suggestions and historical unlabelled searches are excluded. Search sessions and wallets are not unique people or proof of buying demand. Rankings are discovery signals, not valuations. Interest refreshes approximately every minute; minting and trading recheck the blockchain.</p></details><p className="mt-7 hidden text-xs leading-relaxed text-muted-foreground sm:block">Only user-typed searches count; automatic suggestions and historical unlabelled searches are excluded. Search sessions and wallets are not unique people or proof of buying demand. Rankings are discovery signals, not valuations. Interest refreshes approximately every minute; minting and trading recheck the blockchain.</p>
  </>;
}