import { Eye, EyeOff, LoaderCircle, Search } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
import useNameInterest from '@/components/solhandle/names/useNameInterest';
export default function NameInterest({ handle }) {
  const { data, isLoading, error, busy, actionError, toggle, refetch } = useNameInterest(handle);
  return <section className="dark mt-8 rounded-2xl border border-border bg-card p-5 text-left text-foreground" aria-label="Name interest"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Interest in @{handle}</h2><button type="button" onClick={toggle} disabled={busy || isLoading || Boolean(error)} aria-pressed={Boolean(data?.watching)} className="flex items-center gap-2 rounded-lg border border-names-accent/40 bg-names-accent/10 px-4 py-2 text-sm font-medium text-names-accent disabled:opacity-50">{busy ? <LoaderCircle className="h-4 w-4 animate-spin"/> : data?.watching ? <EyeOff className="h-4 w-4"/> : <Eye className="h-4 w-4"/>}{data?.watching ? 'Unwatch' : 'Watch'}</button></div>
    {isLoading ? <p className="mt-4 text-sm text-muted-foreground">Loading interest…</p> : error ? <div className="mt-4"><p className="text-sm text-destructive">Interest is temporarily unavailable.</p><button type="button" onClick={() => refetch()} className="mt-2 text-sm text-names-accent">Try again</button></div> : <><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><p className="flex items-center gap-2 text-2xl font-semibold"><Search className="h-5 w-5 text-names-accent"/>{data?.searches.toLocaleString()}</p><p className="mt-1 text-xs text-muted-foreground">Unique search sessions in 30 days</p></div><div><p className="flex items-center gap-2 text-2xl font-semibold"><Eye className="h-5 w-5 text-names-secondary"/>{data?.watchers.toLocaleString()}</p><p className="mt-1 text-xs text-muted-foreground">Wallets currently watching</p></div></div>{data?.lastSearched && <p className="mt-4 text-xs text-muted-foreground">Last searched {formatDistanceToNow(new Date(data.lastSearched), { addSuffix: true })}</p>}</>}
    <p className="mt-4 text-xs leading-relaxed text-muted-foreground">Search sessions and wallets are not unique people or a valuation. Following signs a message only; your watchlist stays private.</p>{actionError && <p role="alert" className="mt-3 text-sm text-destructive">{actionError}</p>}
  </section>;
}