import { Link } from 'react-router-dom';
import { LoaderCircle } from 'lucide-react';
import NameCard from '@/components/solhandle/names/NameCard';
export default function NamesResults({ state }) {
  const { isLoading, isFetching, error, items, tab, rank, hasNextPage, isFetchingNextPage, fetchNextPage, refetch } = state;
  if (isLoading) return <p className="mt-8 flex items-center gap-2 rounded-2xl border border-border bg-card p-8 text-muted-foreground"><LoaderCircle className="h-5 w-5 animate-spin"/>Loading names and checking live availability…</p>;
  if (error) return <div className="mt-8 rounded-2xl border border-border bg-card p-8"><p role="alert" className="text-destructive">{error.response?.data?.error || 'Names are temporarily unavailable.'}</p><button onClick={() => refetch()} className="mt-4 text-sm text-names-accent">Try again</button></div>;
  return <>{!items.length ? <section className="mt-8 rounded-2xl border border-border bg-card p-8 text-center"><h2 className="text-lg font-semibold">{tab === 'watchlist' ? 'No followed names here yet' : 'No names match this view yet'}</h2><p className="mt-3 text-sm text-muted-foreground">{tab === 'watchlist' ? 'Open a name and select Watch to add it to your private list.' : tab === 'for-sale' ? 'No active listings match your search. Try another name.' : 'Interest rankings show recorded activity only. Try another search or ranking.'}</p><Link to="/" className="mt-5 inline-block text-sm text-names-accent">Search any @handle →</Link></section> : <><div className="mt-7 flex items-center justify-between text-xs text-muted-foreground"><span>{['trending', 'available'].includes(tab) ? `Top names by ${rank === 'watched' ? 'watching wallets' : 'unique search sessions over 30 days'}` : 'Live on-chain status · inspect a name for details'}</span>{isFetching && <LoaderCircle className="h-4 w-4 animate-spin"/>}</div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map(item => <NameCard key={item.handle} item={item}/>)}</div></>}
    {hasNextPage && <div className="mt-8 text-center"><button onClick={() => fetchNextPage()} disabled={isFetchingNextPage} className="rounded-lg border border-border px-5 py-3 text-sm disabled:opacity-50">{isFetchingNextPage ? 'Loading…' : 'Load more names'}</button></div>}
    <p className="mt-7 text-xs leading-relaxed text-muted-foreground">Search sessions and wallets are not unique people or proof of buying demand. Rankings are discovery signals, not valuations. Interest refreshes approximately every minute; minting and trading recheck the blockchain.</p>
  </>;
}