import { pilotRequest, pilotSigner, pilotError } from '../../shared/partnerMintRequest.ts';
import { validatePartnerInput, readPartnerState } from '../../shared/partnerMintChain.ts';
import { fault, b64, quoteDigest, mintInstructions, view } from '../../shared/partnerMintCodec.ts';
import partnerMintMetadata from '../../shared/partnerMintMetadata.ts';
import partnerMintReporting from '../../shared/partnerMintReporting.ts';
export default async function(req) {
  const requestId = crypto.randomUUID();
  try {
    const { base44, user, body, url } = await pilotRequest(req, ['availability', 'quote', 'report', 'reconcile']);
    if (['report', 'reconcile'].includes(body.action)) {
      const result = await partnerMintReporting(base44, user, body, url);
      return Response.json({ ...result, cluster: 'devnet', requestId }, { headers: { 'Cache-Control': 'no-store' } });
    }
    const input = validatePartnerInput(body, body.action === 'quote'), signer = body.action === 'quote' ? pilotSigner() : null;
    const state = await readPartnerState(url, input, signer);
    if (body.action === 'availability') return Response.json({ ...state, cluster: 'devnet', advisoryOnly: true, requestId }, { headers: { 'Cache-Control': 'no-store' } });
    if (!state.available) fault('HANDLE_UNAVAILABLE', 409);
    // Metadata is generated by the protocol, not supplied by partners. No mainnet uploader or signing key is used.
    const uri = await partnerMintMetadata(base44, state);
    const fresh = await readPartnerState(url, input, signer);
    if (!fresh.available) fault('HANDLE_UNAVAILABLE', 409);
    const quote = { ...fresh, cluster: 'devnet', uri, expiresAtUnix: fresh.chainTime + 50 };
    const expiresAt = new Date(quote.expiresAtUnix * 1000).toISOString();
    quote.quoteDigest = b64(await quoteDigest(quote));
    const [verification] = await mintInstructions(quote, signer), offset = view(verification.data).getUint16(2, true);
    quote.quoteSignature = b64(verification.data.slice(offset, offset + 64));
    const intent = await base44.entities.PartnerMintIntent.create({ cluster: 'devnet', admin_user_id: user.id, handle: quote.handle, partner_id: quote.partnerId, wallet: quote.wallet, quote, expires_at: expiresAt, status: 'QUOTED', transaction_signature: '' });
    return Response.json({ quoteId: intent.id, intentId: intent.id, quote, expiresAt, preparationDoesNotReserveHandle: true, requestId }, { headers: { 'Cache-Control': 'no-store' } });
  } catch (error) { return pilotError(error, requestId); }
}