const keys = ["Hi, I'm Atto! Ask me about minting an @handle, trading, SolHandle Pay, the SDK, or the Growth Curve.",'Loading conversation…','Atto is thinking…','Verified $HANDLE mint','Awaiting confirmation','Transaction expired','Transaction failed','View mainnet transaction','Paid','Burned','Treasury','Do not send another mint while this transaction is unresolved. Your receipt is saved on this device.','Check confirmation','View your minted handle','Dismiss','Saved token mint'];
const rows = {
 nl: ['Hoi, ik ben Atto! Vraag me over het minten van een @handle, handelen, SolHandle Pay, de SDK of de groeicurve.','Gesprek laden…','Atto denkt na…','Geverifieerde $HANDLE-mint','Wachten op bevestiging','Transactie verlopen','Transactie mislukt','Bekijk mainnettransactie','Betaald','Verbrand','Treasury','Verstuur geen nieuwe mint zolang deze transactie niet is afgehandeld. Je ontvangstbewijs is opgeslagen op dit apparaat.','Controleer bevestiging','Bekijk je geminte handle','Sluiten','Opgeslagen tokenmint'],
 es: ['¡Hola, soy Atto! Pregúntame sobre crear un @handle, operar, SolHandle Pay, el SDK o la curva de crecimiento.','Cargando conversación…','Atto está pensando…','Mint con $HANDLE verificado','Esperando confirmación','Transacción caducada','Transacción fallida','Ver transacción en mainnet','Pagado','Quemado','Tesorería','No envíes otro mint mientras esta transacción siga sin resolverse. Tu recibo está guardado en este dispositivo.','Comprobar confirmación','Ver tu handle creado','Cerrar','Mint con token guardado'],
 pt: ['Olá, sou Atto! Pergunte sobre criar um @handle, negociar, SolHandle Pay, o SDK ou a curva de crescimento.','Carregando conversa…','Atto está pensando…','Mint com $HANDLE verificado','Aguardando confirmação','Transação expirada','Transação falhou','Ver transação na mainnet','Pago','Queimado','Tesouraria','Não envie outro mint enquanto esta transação não for resolvida. Seu recibo está salvo neste dispositivo.','Verificar confirmação','Ver seu handle criado','Fechar','Mint com token salvo'],
 de: ['Hallo, ich bin Atto! Frag mich zum Minten eines @Handles, zum Handel, zu SolHandle Pay, zum SDK oder zur Wachstumskurve.','Gespräch wird geladen…','Atto denkt nach…','Verifizierter $HANDLE-Mint','Warten auf Bestätigung','Transaktion abgelaufen','Transaktion fehlgeschlagen','Mainnet-Transaktion ansehen','Bezahlt','Verbrannt','Treasury','Sende keinen weiteren Mint, solange diese Transaktion nicht abgeschlossen ist. Dein Beleg ist auf diesem Gerät gespeichert.','Bestätigung prüfen','Geminteten Handle ansehen','Schließen','Gespeicherter Token-Mint'],
 fr: ['Bonjour, je suis Atto ! Posez vos questions sur la création d’un @handle, le trading, SolHandle Pay, le SDK ou la courbe de croissance.','Chargement de la conversation…','Atto réfléchit…','Mint en $HANDLE vérifié','En attente de confirmation','Transaction expirée','Transaction échouée','Voir la transaction sur mainnet','Payé','Brûlé','Trésorerie','N’envoyez pas un autre mint tant que cette transaction n’est pas résolue. Votre reçu est enregistré sur cet appareil.','Vérifier la confirmation','Voir votre handle créé','Fermer','Mint en token enregistré'],
 it: ['Ciao, sono Atto! Chiedimi del mint di un @handle, del trading, di SolHandle Pay, dell’SDK o della curva di crescita.','Caricamento della conversazione…','Atto sta pensando…','Mint con $HANDLE verificato','In attesa di conferma','Transazione scaduta','Transazione non riuscita','Vedi transazione su mainnet','Pagato','Bruciato','Tesoreria','Non inviare un altro mint finché questa transazione non è risolta. La ricevuta è salvata su questo dispositivo.','Verifica conferma','Vedi il tuo handle creato','Chiudi','Mint con token salvato'],
 tr: ['Merhaba, ben Atto! @Handle mint etme, alım satım, SolHandle Pay, SDK veya büyüme eğrisi hakkında soru sorabilirsin.','Sohbet yükleniyor…','Atto düşünüyor…','Doğrulanmış $HANDLE mint işlemi','Onay bekleniyor','İşlemin süresi doldu','İşlem başarısız','Mainnet işlemini görüntüle','Ödenen','Yakılan','Hazine','Bu işlem sonuçlanmadan yeni bir mint gönderme. Makbuzun bu cihazda kayıtlı.','Onayı kontrol et','Mint edilen handle’ını görüntüle','Kapat','Kaydedilmiş token mint işlemi'],
 ja: ['こんにちは、Attoです！@handleのミント、取引、SolHandle Pay、SDK、成長曲線について質問してください。','会話を読み込み中…','Attoが考えています…','確認済み$HANDLEミント','確認待ち','取引の有効期限切れ','取引が失敗しました','Mainnetの取引を見る','支払い','バーン','トレジャリー','この取引が解決するまで新たなミントを送信しないでください。レシートはこの端末に保存されています。','確認状況をチェック','ミントしたハンドルを見る','閉じる','保存されたトークンミント'],
 ko: ['안녕하세요, Atto입니다! @handle 민팅, 거래, SolHandle Pay, SDK 또는 성장 곡선에 대해 질문하세요.','대화 불러오는 중…','Atto가 생각 중입니다…','확인된 $HANDLE 민팅','확인 대기 중','거래 만료','거래 실패','Mainnet 거래 보기','결제액','소각량','트레저리','이 거래가 처리되기 전에는 다른 민팅을 보내지 마세요. 영수증은 이 기기에 저장되어 있습니다.','확인 상태 조회','민팅한 핸들 보기','닫기','저장된 토큰 민팅'],
 vi: ['Xin chào, tôi là Atto! Hãy hỏi về mint @handle, giao dịch, SolHandle Pay, SDK hoặc đường cong tăng trưởng.','Đang tải cuộc trò chuyện…','Atto đang suy nghĩ…','Mint bằng $HANDLE đã xác minh','Đang chờ xác nhận','Giao dịch đã hết hạn','Giao dịch thất bại','Xem giao dịch mainnet','Đã thanh toán','Đã đốt','Ngân quỹ','Không gửi mint khác khi giao dịch này chưa được xử lý xong. Biên nhận được lưu trên thiết bị này.','Kiểm tra xác nhận','Xem handle đã mint','Đóng','Mint bằng token đã lưu']
};
export default Object.fromEntries(Object.entries(rows).map(([locale, values]) => [locale, Object.fromEntries(keys.map((key, i) => [key, values[i]]))]));