const locales = ['nl','es','pt','de','fr','it','tr','ja','ko','vi'];
const rows = [
['Official SolHandle Core assets · 5% protocol royalty · no platform fee','Officiële SolHandle Core-assets · 5% protocolroyalty · geen platformkosten','Activos Core oficiales de SolHandle · 5% de regalías del protocolo · sin comisión de plataforma','Ativos Core oficiais SolHandle · 5% de royalties do protocolo · sem taxa da plataforma','Offizielle SolHandle-Core-Assets · 5% Protokollgebühr · keine Plattformgebühr','Actifs Core officiels SolHandle · 5 % de redevance protocole · sans frais de plateforme','Asset Core ufficiali SolHandle · 5% royalty del protocollo · nessuna commissione della piattaforma','Resmî SolHandle Core varlıkları · %5 protokol telifi · platform ücreti yok','公式SolHandle Coreアセット · プロトコルロイヤリティ5% · プラットフォーム手数料なし','공식 SolHandle Core 자산 · 프로토콜 로열티 5% · 플랫폼 수수료 없음','Tài sản Core SolHandle chính thức · phí bản quyền giao thức 5% · không phí nền tảng'],
['5% protocol royalty · no platform fee','5% protocolroyalty · geen platformkosten','5% de regalías del protocolo · sin comisión de plataforma','5% de royalties do protocolo · sem taxa da plataforma','5% Protokollgebühr · keine Plattformgebühr','5 % de redevance protocole · sans frais de plateforme','5% royalty del protocollo · nessuna commissione della piattaforma','%5 protokol telifi · platform ücreti yok','プロトコルロイヤリティ5% · プラットフォーム手数料なし','프로토콜 로열티 5% · 플랫폼 수수료 없음','Phí bản quyền giao thức 5% · không phí nền tảng'],
['Loading on-chain listings…','On-chain aanbiedingen laden…','Cargando anuncios on-chain…','Carregando anúncios on-chain…','On-Chain-Angebote werden geladen…','Chargement des annonces on-chain…','Caricamento degli annunci on-chain…','Zincir üstü ilanlar yükleniyor…','オンチェーンの出品を読み込み中…','온체인 판매글 불러오는 중…','Đang tải tin bán trên chuỗi…'],
['Listings could not be loaded.','Aanbiedingen konden niet worden geladen.','No se pudieron cargar los anuncios.','Não foi possível carregar os anúncios.','Angebote konnten nicht geladen werden.','Impossible de charger les annonces.','Impossibile caricare gli annunci.','İlanlar yüklenemedi.','出品を読み込めませんでした。','판매글을 불러올 수 없습니다.','Không thể tải tin bán.'],
['No active native listings match these filters.','Geen actieve native aanbiedingen voldoen aan deze filters.','Ningún anuncio nativo activo coincide con estos filtros.','Nenhum anúncio nativo ativo corresponde a estes filtros.','Keine aktiven nativen Angebote entsprechen diesen Filtern.','Aucune annonce native active ne correspond à ces filtres.','Nessun annuncio nativo attivo corrisponde a questi filtri.','Bu filtrelerle eşleşen aktif yerel ilan yok.','条件に一致する有効なネイティブ出品はありません。','필터에 맞는 활성 네이티브 판매글이 없습니다.','Không có tin bán gốc đang hoạt động phù hợp với bộ lọc.'],
['Bid placed successfully.','Bod succesvol geplaatst.','Oferta realizada correctamente.','Oferta feita com sucesso.','Gebot erfolgreich abgegeben.','Offre envoyée avec succès.','Offerta inviata con successo.','Teklif başarıyla verildi.','入札が完了しました。','입찰이 완료되었습니다.','Đã đặt giá thành công.'],
['Connect your wallet first.','Verbind eerst je wallet.','Conecta tu wallet primero.','Conecte sua wallet primeiro.','Verbinde zuerst deine Wallet.','Connectez d’abord votre wallet.','Collega prima il wallet.','Önce cüzdanını bağla.','先にウォレットを接続してください。','먼저 지갑을 연결하세요.','Hãy kết nối ví trước.'],
['Enter a valid SOL amount.','Voer een geldig SOL-bedrag in.','Introduce una cantidad válida de SOL.','Insira um valor válido em SOL.','Gib einen gültigen SOL-Betrag ein.','Saisissez un montant SOL valide.','Inserisci un importo SOL valido.','Geçerli bir SOL tutarı gir.','有効なSOL金額を入力してください。','유효한 SOL 금액을 입력하세요.','Nhập số lượng SOL hợp lệ.'],
['Marketplace transaction failed.','Marktplaatstransactie mislukt.','La transacción del mercado ha fallado.','A transação do mercado falhou.','Marktplatztransaktion fehlgeschlagen.','La transaction du marché a échoué.','Transazione del mercato non riuscita.','Pazar yeri işlemi başarısız.','マーケット取引が失敗しました。','마켓 거래가 실패했습니다.','Giao dịch trên chợ thất bại.'],
['{handle} is now in your wallet and has been removed from the market.','{handle} zit nu in je wallet en is van de marktplaats verwijderd.','{handle} ya está en tu wallet y se ha retirado del mercado.','{handle} está na sua wallet e foi removido do mercado.','{handle} ist jetzt in deiner Wallet und wurde vom Marktplatz entfernt.','{handle} est maintenant dans votre wallet et a été retiré du marché.','{handle} è ora nel tuo wallet ed è stato rimosso dal mercato.','{handle} artık cüzdanında ve pazar yerinden kaldırıldı.','{handle}はウォレットに入り、マーケットから削除されました。','{handle}이 지갑에 추가되었고 마켓에서 제거되었습니다.','{handle} đã nằm trong ví và được gỡ khỏi chợ.'],
['List verified assets directly','Bied geverifieerde assets direct aan','Publica activos verificados directamente','Anuncie ativos verificados diretamente','Verifizierte Assets direkt anbieten','Vendez directement vos actifs vérifiés','Vendi direttamente asset verificati','Doğrulanmış varlıkları doğrudan listele','確認済みアセットを直接出品','검증된 자산 직접 등록','Đăng bán trực tiếp tài sản đã xác minh'],
['Connect your wallet above to view and list your handles.','Verbind hierboven je wallet om je handles te bekijken en aan te bieden.','Conecta tu wallet arriba para ver y publicar tus handles.','Conecte sua wallet acima para ver e anunciar seus handles.','Verbinde oben deine Wallet, um deine Handles anzusehen und anzubieten.','Connectez votre wallet ci-dessus pour voir et vendre vos handles.','Collega il wallet qui sopra per vedere e vendere i tuoi handle.','Handle’larını görüntülemek ve listelemek için yukarıdan cüzdanını bağla.','上でウォレットを接続してハンドルを確認・出品してください。','위에서 지갑을 연결하여 핸들을 확인하고 판매하세요.','Kết nối ví ở trên để xem và đăng bán handle.'],
['Verifying your handles on Solana…','Je handles op Solana verifiëren…','Verificando tus handles en Solana…','Verificando seus handles na Solana…','Deine Handles auf Solana werden geprüft…','Vérification de vos handles sur Solana…','Verifica dei tuoi handle su Solana…','Solana’da handle’ların doğrulanıyor…','Solanaでハンドルを確認中…','Solana에서 핸들 검증 중…','Đang xác minh handle trên Solana…'],
['No verified SolHandles were found for this wallet.','Geen geverifieerde SolHandles gevonden voor deze wallet.','No se encontraron SolHandles verificados para esta wallet.','Nenhum SolHandle verificado foi encontrado nesta wallet.','Für diese Wallet wurden keine verifizierten SolHandles gefunden.','Aucun SolHandle vérifié trouvé pour ce wallet.','Nessun SolHandle verificato trovato per questo wallet.','Bu cüzdan için doğrulanmış SolHandle bulunamadı.','このウォレットに確認済みSolHandleはありません。','이 지갑에서 검증된 SolHandle을 찾지 못했습니다.','Không tìm thấy SolHandle đã xác minh cho ví này.']
];
export default Object.fromEntries(locales.map((locale, i) => [locale, Object.fromEntries(rows.map(row => [row[0], row[i + 1]]))]));