import { useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import { sol } from "@/lib/referralLevels";
import AdminPayoutList from "@/components/solhandle/AdminPayoutList";

export default function AdminReferrals() {
  const [data, setData] = useState(null); const [message, setMessage] = useState(""); const load = () => base44.functions.invoke("manageReferrals", { action: "list" }).then((r) => setData(r.data)); useEffect(() => { load(); }, []);
  const status = async (id, value) => { await base44.functions.invoke("manageReferrals", { action: "status", profile_id: id, status: value }); await load(); }; const bonus = async (id) => { const amount = window.prompt("Bonus amount in SOL:"); if (amount) { await base44.functions.invoke("manageReferrals", { action: "bonus", profile_id: id, amount_sol: amount }); await load(); } }; const flagStatus = async (id, value) => { await base44.functions.invoke("manageReferrals", { action: "flag_status", flag_id: id, status: value }); await load(); };
  const payout = async (profile) => { try { const created = await base44.functions.invoke("manageReferrals", { action: "create_payout", profile_id: profile.id }); const i = created.data.instruction; await navigator.clipboard.writeText(`${i.to} ${i.amountLamports / 1e9} SOL`); const signature = window.prompt(`Send ${i.amountLamports / 1e9} SOL from ${i.from} to ${i.to}. The instruction is copied. Enter the confirmed signature:`); if (signature) await base44.functions.invoke("manageReferrals", { action: "confirm_payout", payout_id: created.data.payout.id, signature }); setMessage("Payout verified on Solana."); await load(); } catch (e) { setMessage(e.response?.data?.error || "Payout is not ready."); } };
  if (!data) return <div className="card-glow mt-8 text-slate-400">Loading referral operations…</div>;
  const o = data.overview; return <section className="card-glow mt-8"><p className="text-sm text-cyan-300">Referral operations</p><h2 className="mt-1 text-2xl font-semibold">Promoters & payouts</h2><div className="mt-5 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Clicks", o.clicks], ["Mints", o.mints], ["Conversion", `${o.conversionRate.toFixed(1)}%`], ["Revenue", sol(o.revenueLamports)], ["Commission", sol(o.commissionLamports)], ["Open flags", o.openFlags]].map(([l,v]) => <div key={l} className="rounded-lg bg-white/5 p-3"><span className="text-xs text-slate-500">{l}</span><b className="mt-1 block">{v}</b></div>)}</div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-slate-500"><tr><th className="p-2">Promoter</th><th>Wallet</th><th>Referrals</th><th>Earnings</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.profiles.map((p) => <tr key={p.id} className="border-t border-white/10"><td className="p-2 text-cyan-200">{p.display_handle}</td><td className="font-mono text-xs">{p.wallet_address.slice(0,4)}…{p.wallet_address.slice(-4)}</td><td>{p.successful_referrals}</td><td>{sol(p.total_earnings_lamports)}</td><td>{p.status}</td><td className="space-x-2 py-2"><button onClick={() => status(p.id, p.status === "ACTIVE" ? "PAUSED" : "ACTIVE")} className="text-violet-200">{p.status === "ACTIVE" ? "Pause" : "Activate"}</button><button onClick={() => status(p.id, "BANNED")} className="text-rose-300">Ban</button><button onClick={() => bonus(p.id)} className="text-amber-300">Bonus</button><button onClick={() => payout(p)} className="text-emerald-300">Pay</button></td></tr>)}</tbody></table></div><AdminPayoutList payouts={data.payouts}/>{data.flags.length > 0 && <div className="mt-6"><h3 className="font-semibold">Open fraud reviews</h3>{data.flags.map((f) => <div key={f.id} className="mt-2 flex items-center justify-between rounded-lg border border-rose-400/20 p-3 text-sm"><span className="text-rose-200">{f.reason} · {f.severity}</span><span className="space-x-3"><button onClick={() => flagStatus(f.id, "CLEARED")} className="text-emerald-300">Clear</button><button onClick={() => flagStatus(f.id, "BLOCKED")} className="text-rose-300">Block</button></span></div>)}</div>}{message && <p className="mt-4 text-sm text-slate-400">{message}</p>}</section>;
}