import { useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";

export default function AdminClaimPolicies() {
  const [policies, setPolicies] = useState([]); const [form, setForm] = useState({ handle: "", official_domain: "", high_risk: true }); const [saving, setSaving] = useState(false);
  const load = async () => setPolicies(await base44.entities.OfficialClaimPolicy.list("handle", 100));
  useEffect(() => { load(); }, []);
  const save = async (event) => { event.preventDefault(); setSaving(true); const handle = form.handle.trim().replace(/^@+/, "").toLowerCase(); const domain = form.official_domain.trim().toLowerCase().replace(/^https?:\/\//, "").replace(/\/.*$/, ""); const existing = policies.find((item) => item.handle === handle); if (existing) await base44.entities.OfficialClaimPolicy.update(existing.id, { official_domain: domain, high_risk: form.high_risk, active: true }); else await base44.entities.OfficialClaimPolicy.create({ handle, official_domain: domain, high_risk: form.high_risk, active: true }); setForm({ handle: "", official_domain: "", high_risk: true }); await load(); setSaving(false); };
  return <section className="card-glow mt-8"><h2 className="font-semibold text-white">Official domain policies</h2><p className="mt-1 text-sm text-slate-500">Applicants cannot change these trusted domains.</p><form onSubmit={save} className="mt-4 grid gap-3 md:grid-cols-[1fr_2fr_auto_auto]"><input required value={form.handle} onChange={(event) => setForm({ ...form, handle: event.target.value })} placeholder="@handle" className="rounded-lg border border-white/10 bg-slate-900 px-3 py-2"/><input required value={form.official_domain} onChange={(event) => setForm({ ...form, official_domain: event.target.value })} placeholder="official-domain.com" className="rounded-lg border border-white/10 bg-slate-900 px-3 py-2"/><label className="flex items-center gap-2 text-sm text-slate-300"><input type="checkbox" checked={form.high_risk} onChange={(event) => setForm({ ...form, high_risk: event.target.checked })}/>High risk</label><button disabled={saving} className="rounded-lg bg-cyan-300 px-4 py-2 font-semibold text-slate-950 disabled:opacity-50">Save</button></form><div className="mt-4 flex flex-wrap gap-2">{policies.map((policy) => <span key={policy.id} className="rounded-full border border-white/10 px-3 py-1 text-xs text-slate-300">@{policy.handle} → {policy.official_domain}{policy.high_risk ? " · high risk" : ""}</span>)}</div></section>;
}