import { useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import AdminEarnNetworkSettings from "@/components/solhandle/AdminEarnNetworkSettings";
import AdminCreatorFeeCycle from "@/components/solhandle/AdminCreatorFeeCycle";

const fields = [["commission_percentage", "Campaign commission %"], ["minimum_payout_sol", "Minimum payout SOL"], ["cookie_duration_days", "Attribution days"], ["payout_hold_hours", "Verification hold hours"]];

export default function AdminReferralSettings() {
  const [settings, setSettings] = useState(null); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { base44.functions.invoke("manageReferralSettings", { action: "get" }).then((res) => setSettings(res.data.settings)); }, []);
  const save = async () => { setSaving(true); setMessage(""); try { const res = await base44.functions.invoke("manageReferralSettings", { action: "update", settings }); setSettings(res.data.settings); setMessage("Ambassador campaign saved."); } catch (error) { setMessage(error.response?.data?.error || "Unable to save settings."); } finally { setSaving(false); } };
  if (!settings) return <section className="card-glow mt-8 text-slate-400">Loading campaign controls…</section>;
  return <section className="card-glow mt-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-cyan-300">Campaign mode</p><h2 className="mt-1 text-2xl font-semibold text-white">Founding Ambassador Program</h2></div><label className="flex items-center gap-3 rounded-xl border border-white/10 px-4 py-3"><input type="checkbox" checked={settings.campaign_enabled !== false} onChange={(e) => setSettings({ ...settings, campaign_enabled: e.target.checked })} className="h-5 w-5 accent-cyan-300"/><span className="font-semibold text-emerald-300">Campaign active</span></label></div><label className="mt-5 block text-xs text-slate-400">Campaign name<input value={settings.campaign_name || ""} onChange={(e) => setSettings({ ...settings, campaign_name: e.target.value })} className="mt-1 w-full rounded-lg border border-white/10 bg-slate-950 px-3 py-2 text-white"/></label><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{fields.map(([key, label]) => <label key={key} className="text-xs text-slate-400">{label}<input type="number" min="0" step="0.1" value={settings[key] ?? ""} onChange={(e) => setSettings({ ...settings, [key]: Number(e.target.value) })} className="mt-1 w-full rounded-lg border border-white/10 bg-slate-950 px-3 py-2 text-white"/></label>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["campaign_start_date", "Start date"], ["campaign_end_date", "End date"]].map(([key, label]) => <label key={key} className="text-xs text-slate-400">{label}<input type="datetime-local" value={(settings[key] || "").slice(0, 16)} onChange={(e) => setSettings({ ...settings, [key]: e.target.value ? new Date(e.target.value).toISOString() : "" })} className="mt-1 w-full rounded-lg border border-white/10 bg-slate-950 px-3 py-2 text-white"/></label>)}</div><div className="mt-5 flex flex-wrap gap-5 text-sm text-slate-300"><label><input type="checkbox" checked={settings.premium_referral_eligible} onChange={(e) => setSettings({ ...settings, premium_referral_eligible: e.target.checked })} className="mr-2 accent-violet-300"/>Premium eligible</label><label><input type="checkbox" checked={settings.payouts_paused} onChange={(e) => setSettings({ ...settings, payouts_paused: e.target.checked })} className="mr-2 accent-rose-300"/>Pause payouts</label></div><AdminEarnNetworkSettings settings={settings} onChange={setSettings}/><AdminCreatorFeeCycle onCarryChange={(value) => setSettings((current) => ({ ...current, creator_fee_carry_lamports: value }))}/><div className="mt-6 flex items-center gap-4"><button onClick={save} disabled={saving} className="rounded-lg bg-cyan-300 px-5 py-2.5 text-sm font-semibold text-slate-950 disabled:opacity-50">{saving ? "Saving…" : "Save campaign"}</button>{message && <span className="text-sm text-slate-400">{message}</span>}</div></section>;
}