import { ExternalLink, Flame } from 'lucide-react';
export default function BurnDashboardHistory({ records, hasMore, loadingMore, onLoadMore }) {
  return <section className="mt-8 rounded-2xl border border-border bg-card p-5 sm:p-6" aria-labelledby="burn-history-title">
    <h2 id="burn-history-title" className="text-xl font-semibold">Burn history · on-chain proof</h2>
    <p className="mt-2 text-sm text-muted-foreground">Confirmed burns only. Purchases, treasury transfers and planned rewards are not counted as burns.</p>
    {!records.length ? <div className="mt-6 rounded-xl border border-burn-accent/20 p-6 text-center"><Flame aria-hidden="true" className="mx-auto h-8 w-8 text-burn-accent"/><p className="mt-3 font-medium">No burns recorded yet</p><p className="mt-2 text-sm text-muted-foreground">A confirmed and processed $HANDLE mint burn or a recorded on-chain burn will appear here.</p></div> : <div className="mt-5 divide-y divide-border">{records.map(item => <article key={item.signature} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between">
      <div className="min-w-0"><p className="flex items-center gap-2 font-semibold text-burn-accent"><Flame aria-hidden="true" className="h-4 w-4 shrink-0"/>{Number(item.amount).toLocaleString('en-US', { maximumFractionDigits: 9 })} $HANDLE burned</p><p className="mt-1 break-words text-sm">{item.source === 'mint' ? `Automatic mint burn · @${item.handle}` : item.source === 'growth' ? `Growth reward burn · Cycle ${item.cycle}` : 'Recorded on-chain burn'}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(item.occurredAt).toLocaleString('en-GB')}</p></div>
      <a href={`https://solscan.io/tx/${item.signature}`} target="_blank" rel="noopener noreferrer" className="inline-flex shrink-0 items-center gap-2 rounded-lg border border-burn-secondary/30 px-3 py-2 text-sm text-burn-secondary" aria-label={`View burn transaction ${item.signature}`}>{item.signature.slice(0, 6)}…{item.signature.slice(-6)}<ExternalLink aria-hidden="true" className="h-4 w-4"/></a>
    </article>)}</div>}
    {hasMore && <button onClick={onLoadMore} disabled={loadingMore} className="mt-4 rounded-lg border border-border px-4 py-2 text-sm disabled:opacity-50">{loadingMore ? 'Loading burns…' : 'Load more burns'}</button>}
  </section>;
}