import { useState } from "react";

const content = {
  sdk: { title: "Official SDK · Live on npm", note: "Install solhandle-sdk@1.0.0 with @solana/web3.js. Use a dedicated Mainnet RPC in production and resolve again immediately before constructing a transaction.", code: 'npm install solhandle-sdk @solana/web3.js\n\nimport { Connection } from "@solana/web3.js";\nimport { resolveRecipient } from "solhandle-sdk";\n\nconst connection = new Connection("https://your-mainnet-rpc.example", "confirmed");\nconst recipient = await resolveRecipient("@ansem", { connection });\nif (!recipient) throw new Error("Handle not found");\nif (recipient.kind === "solhandle" && !recipient.safeForNativeSol) {\n  throw new Error("Unsafe native SOL destination");\n}\nconsole.log(recipient.addressString);' },
  api: { title: "REST convenience layer · Mainnet", note: "Forward and reverse resolution use the Mainnet protocol. Reverse lookup returns a handle only when the wallet still owns its verified Primary Handle asset. API responses are convenient, but Solana remains authoritative.", code: 'POST https://sol-handle-core.base44.app/functions/resolveSolHandle\n{ "handle": "@solhandle" }\n\nPOST https://sol-handle-core.base44.app/functions/reverseResolveSolHandle\n{ "address": "7xQu...R20q" }' },
  chain: { title: "Direct Mainnet on-chain · Working", note: "The npm SDK performs these checks without using the SolHandle website, database or REST API. Advanced integrations may reproduce them directly against a Mainnet RPC node.", code: 'handle PDA: ["handle", normalizedHandle]\nasset PDA: ["asset", normalizedHandle]\nprimary PDA: ["primary", wallet]\n\nProgram: B7xiwfxGcR2Xz7tcUKrkB8Ly6NV8jU7LH1m6GJZRUuf\nCollection: 7XZzcbeFBxQA63n9avz44vnbpv34hDGYyHfCDmTdPBJP' }
};
export default function DeveloperIntegrationTabs() {
  const [tab, setTab] = useState("sdk"); const selected = content[tab];
  return <section className="mt-10"><div className="flex flex-wrap gap-2">{[["sdk","SDK"],["api","REST API"],["chain","Direct On-chain"]].map(([value,label]) => <button key={value} onClick={() => setTab(value)} className={`rounded-full px-4 py-2 text-sm ${tab === value ? "bg-cyan-300 text-slate-950" : "border border-white/10 text-slate-300"}`}>{label}</button>)}</div><div className="mt-4 rounded-2xl border border-white/10 bg-slate-950/70 p-5"><h2 className="text-xl font-semibold">{selected.title}</h2><p className="mt-2 text-sm leading-relaxed text-slate-400">{selected.note}</p><pre className="mt-5 overflow-x-auto rounded-xl bg-black/40 p-4 text-sm leading-relaxed text-cyan-100"><code>{selected.code}</code></pre></div></section>;
}