import { BadgeCheck, ShieldCheck } from "lucide-react";
import useDiscordVerification from "@/hooks/useDiscordVerification";

const walletOptions = ["Phantom", "Solflare", "Backpack"];

export default function DiscordVerifyCard() {
  const token = new URLSearchParams(window.location.search).get("token") || "";
  const { connected, connecting, address, walletName, walletChoice, chooseWallet, changeWallet, verify, loading, error, handle } = useDiscordVerification(token);
  if (handle) return <section className="card-glow max-w-xl text-center"><BadgeCheck className="mx-auto h-12 w-12 text-emerald-300"/><h1 className="mt-4 text-2xl font-semibold text-white">Verification complete</h1><p className="mt-3 text-slate-300">{handle} is verified. The Handle Holder role has been added in Discord.</p></section>;
  return <section className="card-glow max-w-xl"><div className="flex h-12 w-12 items-center justify-center rounded-xl border border-cyan-300/30 bg-cyan-300/10"><ShieldCheck className="h-6 w-6 text-cyan-200"/></div><h1 className="mt-5 text-2xl font-semibold text-white">Verify your SolHandle</h1><p className="mt-3 text-sm leading-6 text-slate-400">Choose the wallet that owns an active SolHandle and sign a free message. No transaction is created and no funds can move.</p>{!token && <p className="mt-5 rounded-lg border border-amber-300/20 bg-amber-300/10 p-3 text-sm text-amber-100">This link is incomplete. Run /verify in the SolHandle Discord server.</p>}{!walletChoice ? <div className="mt-6 grid gap-2">{walletOptions.map((name) => <button key={name} type="button" onClick={() => chooseWallet(name)} className="rounded-lg border border-white/10 px-4 py-3 text-left font-semibold text-white hover:border-cyan-300/40">Connect {name}</button>)}</div> : <div className="mt-6"><div className="mb-3 rounded-lg border border-white/10 bg-white/[0.03] p-3 text-xs text-slate-300"><b className="text-white">{walletName || walletChoice}</b>{address && <span className="ml-2 font-mono">{address.slice(0,4)}…{address.slice(-4)}</span>}<button type="button" onClick={changeWallet} className="float-right text-cyan-300">Change</button></div><button type="button" disabled={!token || !connected || connecting || loading} onClick={verify} className="w-full rounded-lg bg-gradient-to-r from-cyan-300 to-violet-300 px-5 py-3 font-semibold text-slate-950 disabled:opacity-50">{connecting ? "Connecting…" : loading ? "Verifying…" : "Sign and verify ownership"}</button></div>}{error && <p className="mt-4 text-sm text-rose-300">{error}</p>}</section>;
}