import { Link } from "react-router-dom";
import { Image } from "@/components/ui/image";

export default function Footer() {
  return <footer className="relative overflow-hidden border-t border-cyan-300/25 bg-[#030615] px-5 py-10 text-sm text-slate-300 shadow-[0_-12px_40px_rgba(45,212,191,0.10)] md:px-9">
    <Image src="https://media.base44.com/images/public/6a86b7e4bcec5dfac8ee9a44/3ccebb01d_image.png" alt="Abstract cyan and violet Solana waves" className="pointer-events-none absolute inset-0 h-full w-full opacity-65" fittingType="fill"/>
    <div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-[#030615]/75 via-[#030615]/45 to-[#030615]/80"/>
    <div className="relative z-10 mx-auto grid max-w-7xl gap-8 md:grid-cols-[1.4fr_1fr_1fr]">
      <div><p className="text-base font-semibold text-white">SolHandle</p><p className="mt-3 max-w-sm leading-relaxed">NFT-native identity infrastructure for Solana, live on Mainnet Beta. Claim, own and use your unique on-chain handle.</p></div>
      <nav><p className="mb-3 font-medium text-white">Explore</p><div className="space-y-2"><Link to="/docs" className="block hover:text-cyan-200">Documentation</Link><Link to="/developers" className="block hover:text-cyan-200">Developers</Link><Link to="/roadmap" className="block hover:text-cyan-200">Roadmap</Link><Link to="/integrations" className="block hover:text-cyan-200">Integration Center</Link><Link to="/faq" className="block hover:text-cyan-200">FAQ</Link><Link to="/contact" className="block hover:text-cyan-200">Contact</Link></div></nav>
      <nav><p className="mb-3 font-medium text-white">Legal</p><div className="space-y-2"><Link to="/legal" className="block hover:text-cyan-200">Legal notice & disclaimer</Link><Link to="/privacy" className="block hover:text-cyan-200">Privacy policy</Link><Link to="/referral-terms" className="block hover:text-cyan-200">Share & Earn Terms</Link></div></nav>
    </div>
    <div className="relative z-10 mx-auto mt-8 flex max-w-7xl flex-col gap-2 border-t border-white/10 pt-5 text-xs sm:flex-row sm:justify-between"><span>© 2026 SolHandle. Live on Solana Mainnet.</span><div className="flex flex-wrap items-center gap-4"><a href="https://discord.gg/X4UHSTWuk" target="_blank" rel="noreferrer" aria-label="Join the SolHandle Discord" title="Discord" className="inline-flex h-8 w-8 items-center justify-center overflow-hidden rounded-full border border-violet-400/30 bg-slate-950 hover:border-violet-300/60"><Image src="https://media.base44.com/images/public/6a86b7e4bcec5dfac8ee9a44/86f082e4e_image.png" alt="Discord" className="h-5 w-5" fittingType="fit"/></a><a href="https://x.com/Solhandle" target="_blank" rel="noreferrer" aria-label="Follow SolHandle on X" title="X" className="inline-flex h-8 w-8 items-center justify-center overflow-hidden rounded-full border border-white/10 bg-slate-950 hover:border-cyan-300/40"><Image src="https://media.base44.com/images/public/6a86b7e4bcec5dfac8ee9a44/fc43c0a5c_image.png" alt="X" className="h-9 w-9 shrink-0 max-w-none" fittingType="fill"/></a><a href="https://magiceden.io/marketplace/solhandle" target="_blank" rel="noreferrer" className="hover:text-cyan-200">Magic Eden</a><Link to="/contact" className="hover:text-cyan-200">Contact</Link></div></div>
  </footer>;
}