const rewards = [
  { at: 20, title: '10× DEX Screener Boost', detail: 'Planned promotion of $HANDLE on DEX Screener.' },
  { at: 40, title: '5 million $HANDLE burn', detail: 'Planned burn of 5 million $HANDLE; execution only after confirming the token reserve and providing on-chain proof of the burn.' },
  { at: 60, title: '30× DEX Screener Boost', detail: 'Larger planned visibility campaign for $HANDLE.' },
  { at: 80, title: 'Draw: 5 two-letter mint slots', detail: 'Planned draw for five two-letter handle mint slots, subject to availability, funding, and published rules.' },
  { at: 100, title: '50× DEX Screener Boost', detail: 'Planned boost to close out the cycle.' }
];
export default function GrowthMilestones({ progress, cycle }) {
  return <section className="mt-10"><h2 className="text-2xl font-semibold text-white">Milestone rewards</h2><p className="mt-2 text-sm text-slate-400">Reaching a milestone unlocks a plan, not an automatically completed action. Boosts, the token burn, and the draw only proceed after funding, terms, and proof of execution are confirmed. Boost × refers to DEX Screener boost strength, not a prediction of token price.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{rewards.map(reward => { const reached = progress >= reward.at; return <div key={reward.at} className="rounded-xl border border-white/10 bg-slate-950/70 px-4 py-4"><div className="flex items-center gap-3"><span className={reached ? 'font-mono text-emerald-300' : 'font-mono text-slate-500'}>{reward.at}%</span><p className="text-sm font-semibold text-white">{reward.title}</p></div><p className="mt-2 text-xs leading-relaxed text-slate-400">{reward.detail}</p><p className="mt-2 text-xs text-slate-500">{reached ? 'Goal reached · execution not yet confirmed' : `Not yet reached · cycle ${cycle}`}</p></div>; })}</div></section>;
}