import useHandlePaymentTest from '@/components/solhandle/useHandlePaymentTest';
import HandlePaymentTestReceipt from '@/components/solhandle/HandlePaymentTestReceipt';
import formatHandleTokens from '@/components/solhandle/formatHandleTokens';
import HandlePaymentTestBlocker from '@/components/solhandle/HandlePaymentTestBlocker';
export default function HandlePaymentTestPanel() {
  const test = useHandlePaymentTest(), quote = test.quote;
  const configurationConfirmed = test.result?.kind === 'submit_configuration' && test.result.status === 'confirmed';
  const locked = Boolean(test.busy || (test.result && !configurationConfirmed)), tokens = raw => formatHandleTokens(raw, quote.decimals);
  const canMint = test.status?.enabledOnChain && quote?.quoteEligible && quote.sufficientBalance && quote.solReferenceLamports <= 10000000 && test.acknowledged && test.wallet;
  return <section className="dark mt-6 rounded-2xl border border-border bg-card p-5 text-card-foreground">
    <h2 className="text-xl font-semibold">Administrator · $HANDLE mainnet test</h2>
    <p className="mt-2 text-sm text-muted-foreground">Real funds, even in the preview. Limited to a mint price of 0.01 SOL or less, paid in $HANDLE. SOL is still needed for network and NFT account costs. Maximum reference price impact: 10%, with no discount. This panel remains administrator-only; public payments use the claim dialog.</p>
    {test.busy && <p role="status" className="mt-3 text-sm text-muted-foreground">{test.busy}</p>}
    {test.error && <p role="alert" className="mt-3 break-words text-sm text-destructive">{test.error}</p>}
    {test.status && <div className="mt-4 text-sm"><p>{test.status.enabledOnChain ? 'On-chain token payments enabled.' : test.status.reason}</p><p className="mt-2 break-all text-muted-foreground">Connected wallet: {test.wallet || 'Connect a wallet using the header.'}</p>{!test.status.enabledOnChain && <p className="mt-2 break-all text-muted-foreground">Configuration requires the protocol authority: {test.status.authority}. If simulation reports an unknown instruction, the updated program must first be deployed.</p>}</div>}
    <label className="mt-4 flex items-start gap-2 text-sm"><input type="checkbox" checked={test.acknowledged} disabled={locked} onChange={event => test.setAcknowledged(event.target.checked)} className="mt-1"/>I understand that I am approving real mainnet transactions with real tokens and SOL costs.</label>
    {!test.status?.enabledOnChain && <button onClick={test.configure} disabled={locked || !test.status || !test.acknowledged || test.wallet !== test.status.authority} className="mt-4 rounded-lg bg-primary px-4 py-3 font-semibold text-primary-foreground disabled:opacity-50">Configure with protocol wallet</button>}
    <form onSubmit={event => { event.preventDefault(); test.getQuote(); }} className="mt-5 flex flex-col gap-3 sm:flex-row"><label className="flex flex-1 items-center rounded-lg border border-input px-3">@<input aria-label="Test handle" value={test.handle} onChange={event => test.setHandle(event.target.value)} placeholder="ansem" maxLength={21} disabled={locked} className="w-full bg-transparent px-2 py-3 outline-none"/></label><button disabled={locked || !test.wallet || !test.handle.trim()} className="rounded-lg border border-border px-4 py-3 disabled:opacity-50">Review token quote</button></form>
    {quote && <div className="mt-4 text-sm"><dl className="grid gap-3 sm:grid-cols-3"><div><dt className="text-muted-foreground">Maximum token payment</dt><dd>{tokens(quote.totalRaw)} $HANDLE</dd></div><div><dt className="text-muted-foreground">Burn · 50%, rounded down</dt><dd>{tokens(quote.burnRaw)} $HANDLE</dd></div><div><dt className="text-muted-foreground">Treasury · remainder</dt><dd>{tokens(quote.treasuryRaw)} $HANDLE</dd></div></dl><p className="mt-3 text-muted-foreground">SOL reference: {quote.solReferenceLamports / 1e9} SOL · Wallet balance: {tokens(quote.walletBalanceRaw)} $HANDLE. Exact token amounts are enforced; display abbreviations do not change the payment.</p>{quote.solReferenceLamports > 10000000 && <p className="mt-3 text-destructive">Choose a handle priced at 0.01 SOL or less.</p>}{quote.quoteWarning && <p className={quote.quoteEligible ? 'mt-3 text-muted-foreground' : 'mt-3 text-destructive'}>{quote.quoteWarning}</p>}{!quote.sufficientBalance && <p className="mt-3 text-destructive">Insufficient spendable $HANDLE balance.</p>}</div>}
    <HandlePaymentTestBlocker test={test}/>
    <div className="mt-5 flex flex-wrap gap-3"><button onClick={test.mint} disabled={locked || !canMint} className="rounded-lg bg-primary px-5 py-3 font-semibold text-primary-foreground disabled:opacity-50">Approve $HANDLE mint test</button><button onClick={test.refresh} disabled={Boolean(test.busy)} className="rounded-lg border border-border px-4 py-3 disabled:opacity-50">Refresh status</button></div>
    <HandlePaymentTestReceipt result={test.result} busy={test.busy} onConfirm={test.confirm} onContinue={test.clearResult}/>
  </section>;
}