import { useEffect, useState } from "react";
import { useWallet } from "@solana/wallet-adapter-react";
import { base44 } from "@/api/base44Client";
import MarketplaceAction from "@/components/solhandle/MarketplaceAction";
import { lamportsToSol } from "@/lib/marketplace";

export default function HandleMarketplacePanel({ handle, asset, owner }) {
  const { publicKey } = useWallet(); const wallet = publicKey?.toBase58() || ""; const [listing, setListing] = useState(null); const [bids, setBids] = useState([]);
  const load = () => Promise.all([base44.entities.NativeListing.filter({ asset_address: asset, status: "ACTIVE" }, "-created_at", 1), base44.entities.NativeBid.filter({ asset_address: asset, status: "ACTIVE" }, "-amount_lamports", 50)]).then(([listed, offered]) => { setListing(listed[0] || null); setBids(offered); });
  useEffect(() => { if (asset) load(); }, [asset]); if (!asset) return null; const owns = wallet === owner;
  return <section className="card-glow mt-8 text-left"><p className="text-xs uppercase tracking-wider text-violet-300">Native marketplace</p>{listing ? <div className="mt-4"><div className="mb-4 flex items-end justify-between"><span className="text-slate-400">Listed price</span><strong className="text-xl text-emerald-300">{lamportsToSol(listing.price_lamports)} SOL</strong></div>{owns ? <MarketplaceAction action="delist" label="Delist handle" handle={handle} asset={asset} seller={owner} onComplete={load}/> : <MarketplaceAction action="buy" label="Buy now" handle={handle} asset={asset} seller={owner} amount={listing.price_lamports} onComplete={load}/>}</div> : owns ? <div className="mt-4"><p className="mb-3 text-sm text-slate-400">Set a fixed SOL price for direct purchase.</p><MarketplaceAction action="list" label="List for sale" handle={handle} asset={asset} seller={owner} onComplete={load}/></div> : <div className="mt-4"><p className="mb-3 text-sm text-slate-400">Make an escrowed SOL offer to the owner.</p><MarketplaceAction action="bid" label="Place bid" handle={handle} asset={asset} seller={owner} onComplete={load}/></div>}<div className="mt-6 border-t border-white/10 pt-5"><h3 className="font-medium">Active bids</h3>{bids.length ? <div className="mt-3 space-y-3">{bids.map((bid) => <div key={bid.id} className="rounded-lg border border-white/10 p-3"><div className="mb-3 flex justify-between text-sm"><span className="text-slate-400">{bid.bidder.slice(0,4)}…{bid.bidder.slice(-4)}</span><strong>{lamportsToSol(bid.amount_lamports)} SOL</strong></div>{owns && <MarketplaceAction action="accept_bid" label="Accept bid" handle={handle} asset={asset} seller={owner} bidder={bid.bidder} amount={bid.amount_lamports} onComplete={load}/>} {wallet === bid.bidder && <MarketplaceAction action="cancel_bid" label="Cancel bid" handle={handle} asset={asset} bidder={bid.bidder} onComplete={load}/>}</div>)}</div> : <p className="mt-2 text-sm text-slate-500">No active bids.</p>}</div></section>;
}