import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useWallet } from '@solana/wallet-adapter-react';
import { authorizedPayments } from '@/lib/payAuth';
export default function IncomingPayments({ primaryHandle }) {
  const { publicKey, signMessage } = useWallet();
  const [items, setItems] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const load = async () => { setBusy(true); setError(''); try { const data = await authorizedPayments('incoming', publicKey, signMessage); setItems(data.payments.filter(p => p.handle === primaryHandle)); } catch (e) { setError(e.response?.data?.error || e.message); } finally { setBusy(false); } };
  return <section className="card-glow mt-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-cyan-300">SolHandle Pay</p><h2 className="mt-1 text-xl font-semibold text-white">Incoming payments {primaryHandle && <span className="text-cyan-200">to {primaryHandle}</span>}</h2></div><button type="button" onClick={load} disabled={busy || !publicKey || !primaryHandle} className="rounded-lg border border-cyan-300/40 px-4 py-2 text-sm font-semibold text-cyan-200 disabled:opacity-50">{busy ? 'Loading…' : items ? 'Refresh payments' : 'View payments'}</button></div>{!primaryHandle && <p className="mt-3 text-sm text-slate-400">Set a primary handle to see its incoming payments.</p>}{error && <p role="alert" className="mt-3 text-sm text-rose-300">{error} <button onClick={load} className="underline">Retry</button></p>}{items && (items.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{items.map(p => <Link key={p.id} to={`/pay?receipt=${encodeURIComponent(p.id)}`} className="min-w-0 rounded-xl border border-white/10 bg-slate-900/70 p-4 transition hover:border-cyan-300/50"><p className="text-lg font-semibold text-emerald-200">+{(p.amount_lamports / 1e9).toLocaleString('en-US', { maximumFractionDigits: 9 })} SOL</p><p className="mt-1 text-sm text-white">From {p.sender_primary_handle || `${p.sender_wallet.slice(0, 6)}…${p.sender_wallet.slice(-4)}`}</p><p className="mt-2 truncate text-xs text-slate-400">{p.tx_signature}</p><span className="mt-2 inline-block text-xs text-cyan-300">View receipt & Explorer →</span></Link>)}</div> : <p className="mt-3 text-sm text-slate-400">No confirmed payments to {primaryHandle} yet.</p>)}</section>;
}