import { useState } from "react";
import { useWallet } from "@solana/wallet-adapter-react";
import { executeMarketplaceAction, solToLamports } from "@/lib/marketplace";

export default function MarketplaceAction({ action, handle, asset, seller, bidder, amount, label, onComplete }) {
  const { publicKey, signTransaction } = useWallet(); const [price, setPrice] = useState(amount || ""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const needsAmount = action === "list" || action === "bid";
  const submit = async () => { if (!publicKey) return setError("Connect your wallet first."); const lamports = needsAmount ? solToLamports(price) : Number(amount || 0); if ((needsAmount || action === "buy" || action === "accept_bid") && (!Number.isFinite(lamports) || lamports <= 0)) return setError("Enter a valid SOL amount."); setBusy(true); setError(""); try { const result = await executeMarketplaceAction({ action, handle, assetAddress: asset, amountLamports: lamports, seller, bidder, wallet: publicKey, signTransaction }); onComplete?.(result); } catch (caught) { setError(caught.message || "Marketplace transaction failed."); } finally { setBusy(false); } };
  return <div className="space-y-2">{needsAmount && <div className="flex rounded-lg border border-white/10 bg-slate-950"><input value={price} onChange={(event) => setPrice(event.target.value)} inputMode="decimal" placeholder="Price in SOL" className="min-w-0 flex-1 bg-transparent px-3 py-2 text-sm text-white outline-none"/><span className="px-3 py-2 text-sm text-slate-400">SOL</span></div>}<button type="button" onClick={submit} disabled={busy} className="w-full rounded-lg bg-gradient-to-r from-cyan-300 to-violet-400 px-4 py-2.5 text-sm font-semibold text-slate-950 disabled:opacity-50">{busy ? "Confirming…" : label}</button>{error && <p className="text-xs text-rose-300">{error}</p>}</div>;
}