import { useState } from "react";
import { useWallet } from "@solana/wallet-adapter-react";
import { executeMarketplaceAction, solToLamports } from "@/lib/marketplace";

export default function MarketplaceAction({ action, handle, asset, seller, bidder, amount, label, onComplete, cardLayout = false }) {
  const { publicKey, signTransaction } = useWallet(); const [price, setPrice] = useState(amount || ""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const needsAmount = action === "list" || action === "bid";
  const [bidOpen, setBidOpen] = useState(false);
  const revealBid = cardLayout && action === "bid";
  const handleClick = () => { if (revealBid && !bidOpen && window.matchMedia('(max-width: 1279px)').matches) { setBidOpen(true); return; } submit(); };
  const submit = async () => { if (!publicKey) return setError("Connect your wallet first."); const lamports = needsAmount ? solToLamports(price) : Number(amount || 0); if ((needsAmount || action === "buy" || action === "accept_bid") && (!Number.isFinite(lamports) || lamports <= 0)) return setError("Enter a valid SOL amount."); setBusy(true); setError(""); try { const result = await executeMarketplaceAction({ action, handle, assetAddress: asset, amountLamports: lamports, seller, bidder, wallet: publicKey, signTransaction }); onComplete?.(result); } catch (caught) { setError(caught.response?.data?.error || caught.message || "Marketplace transaction failed."); } finally { setBusy(false); } };
  return <div className={cardLayout ? "contents" : needsAmount ? "flex flex-nowrap items-stretch gap-2" : "space-y-2"}>{needsAmount && <div className={`${cardLayout ? "order-1 col-span-1 sm:col-span-2" : "min-w-0 flex-1"} ${revealBid && !bidOpen ? 'hidden sm:flex' : 'flex'} rounded-lg border border-white/10 bg-slate-950`}><input type="number" min="0" step="any" value={price} onChange={(event) => setPrice(event.target.value)} inputMode="decimal" placeholder="Price in SOL" className="min-w-0 flex-1 bg-transparent px-2 py-2 text-sm text-white outline-none sm:min-w-20 sm:px-3"/><span className="px-2 py-2 text-xs text-slate-400 sm:px-3 sm:text-sm">SOL</span></div>}<button type="button" onClick={handleClick} disabled={busy} className={`${cardLayout ? action === "bid" ? "order-3 w-full" : "order-2 w-full" : needsAmount ? "shrink-0" : "w-full"} rounded-lg bg-gradient-to-r from-cyan-300 to-violet-400 px-4 py-2.5 text-sm font-semibold text-slate-950 shadow-sm shadow-violet-950/30 disabled:opacity-50`}>{busy ? "Confirming…" : revealBid && bidOpen ? <><span className="sm:hidden">Submit bid</span><span className="hidden sm:inline">{label}</span></> : label}</button>{error && <p className={`${cardLayout ? "order-4 col-span-1 sm:col-span-2" : "w-full"} text-xs text-white`}>{error}</p>}</div>;
}