import { useState } from "react";
import { useWallet } from "@solana/wallet-adapter-react";
import { executeMarketplaceAction, solToLamports } from "@/lib/marketplace";

export default function MarketplaceAction({ action, handle, asset, seller, bidder, amount, label, onComplete, cardLayout = false }) {
  const { publicKey, signTransaction } = useWallet(); const [price, setPrice] = useState(amount || ""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const needsAmount = action === "list" || action === "bid";
  const submit = async () => { if (!publicKey) return setError("Connect your wallet first."); const lamports = needsAmount ? solToLamports(price) : Number(amount || 0); if ((needsAmount || action === "buy" || action === "accept_bid") && (!Number.isFinite(lamports) || lamports <= 0)) return setError("Enter a valid SOL amount."); setBusy(true); setError(""); try { const result = await executeMarketplaceAction({ action, handle, assetAddress: asset, amountLamports: lamports, seller, bidder, wallet: publicKey, signTransaction }); onComplete?.(result); } catch (caught) { setError(caught.response?.data?.error || caught.message || "Marketplace transaction failed."); } finally { setBusy(false); } };
  return <div className={cardLayout ? "contents" : needsAmount ? "flex flex-wrap items-stretch gap-2" : "space-y-2"}>{needsAmount && <div className={`${cardLayout ? "order-1 col-span-2" : "min-w-40 flex-1"} flex rounded-lg border border-white/10 bg-slate-950`}><input type="number" min="0" step="any" value={price} onChange={(event) => setPrice(event.target.value)} inputMode="decimal" placeholder="Price in SOL" className="min-w-20 flex-1 bg-transparent px-3 py-2 text-sm text-white outline-none"/><span className="px-3 py-2 text-sm text-slate-400">SOL</span></div>}<button type="button" onClick={submit} disabled={busy} className={`${cardLayout ? action === "bid" ? "order-3 w-full" : "order-2 w-full" : needsAmount ? "shrink-0" : "w-full"} rounded-lg bg-gradient-to-r from-cyan-300 to-violet-400 px-4 py-2.5 text-sm font-semibold text-slate-950 shadow-sm shadow-violet-950/30 disabled:opacity-50`}>{busy ? "Confirming…" : label}</button>{error && <p className={`${cardLayout ? "order-4 col-span-2" : "w-full"} text-xs text-black`}>{error}</p>}</div>;
}