import { useState } from "react";
import { useWallet } from "@solana/wallet-adapter-react";
import { CheckCircle2, Copy } from "lucide-react";
import { base44 } from "@/api/base44Client";

export default function OfficialClaimVerification({ claim, step, onStepChange }) {
  const { publicKey, signMessage } = useWallet();
  const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [domainChecked, setDomainChecked] = useState(false);
  const checkDomain = async () => { setBusy("domain"); setError(""); try { const response = await base44.functions.invoke("verifyOfficialClaimDomain", { request_id: claim.requestId }); if(response.data.verified) onStepChange(3); } catch (caught) { const message = caught.response?.data?.error || caught.message || "Domain verification failed."; if (message.includes("Challenge not found")) { setDomainChecked(true); setError("The DNS record is not visible yet. DNS propagation can take from a few minutes to several hours. Wait a little, then check again."); } else setError(message); } finally { setBusy(""); } };
  const verifyWallet = async () => {
    setError("");
    if (!publicKey) { window.dispatchEvent(new Event("solhandle:connect-wallet")); return; }
    if (publicKey.toBase58() !== claim.recipientWallet) { setError("Connect the recipient wallet entered in the request."); return; }
    if (!signMessage) { setError("This wallet does not support message signing."); return; }
    setBusy("wallet");
    try { const bytes = await signMessage(new TextEncoder().encode(claim.message)); const signatureBase64 = btoa(String.fromCharCode(...bytes)); const response = await base44.functions.invoke("verifyOfficialClaimWallet", { request_id: claim.requestId, signature_base64: signatureBase64 }); if(response.data.verified) onStepChange(4); }
    catch (caught) { setError(caught.response?.data?.error || caught.message); } finally { setBusy(""); }
  };
  if(step === 2) return <div className="space-y-4 text-sm"><div><h3 className="font-semibold text-white">Verify official domain</h3><p className="mt-1 text-slate-400">The approved domain for @{claim.handle || "this handle"} is <b className="text-white">{claim.domain}</b>. Your supporting profile URL does not change this domain.</p></div><div className="space-y-3 rounded-xl border border-cyan-300/20 bg-cyan-300/5 p-4"><p className="text-slate-300">Create one DNS record with these exact details:</p><CopyField label="Record type" value="TXT"/><p className="text-xs leading-relaxed text-slate-300">Choose exactly one host option, depending on your DNS provider:</p><CopyField label={`Host option 1 — ${claim.domain} is already appended`} value="_solhandle"/><CopyField label="Host option 2 — full hostname required" value={`_solhandle.${claim.domain}`}/><CopyField label="TXT value — same for both options" value={claim.challenge}/><p className="text-xs leading-relaxed text-slate-400">If the provider shows <b>{claim.domain}</b> beside or after the host field, choose option 1. Otherwise choose option 2. Never combine both, and do not enter www.{claim.domain}.</p></div><div className="rounded-lg border border-white/10 p-3 text-xs text-slate-400">Alternative: publish only the TXT value at <b className="text-slate-200">https://{claim.domain}/.well-known/solhandle-verification.txt</b></div><p className="text-xs leading-relaxed text-amber-200/80">DNS changes are not always immediate. Propagation can take a few minutes to several hours, so you may need to check more than once.</p>{error && <p className="rounded-lg border border-amber-300/20 bg-amber-300/5 p-3 text-amber-200">{error}</p>}<button onClick={checkDomain} disabled={Boolean(busy)} className="w-full rounded-lg bg-gradient-to-r from-emerald-300 via-cyan-400 to-violet-500 py-3 font-semibold text-slate-950 disabled:opacity-60">{busy === "domain" ? "Checking DNS…" : domainChecked ? "Check DNS again" : "Verify domain and continue"}</button></div>;
  if(step === 3) return <div className="space-y-4 text-sm"><div><h3 className="font-semibold text-white">Verify recipient wallet</h3><p className="mt-1 text-slate-400">Connect the recipient wallet and sign the claim message. This does not create a transaction.</p></div><div className="rounded-xl border border-violet-300/20 bg-violet-300/5 p-4"><span className="text-slate-400">Recipient wallet</span><code className="mt-2 block break-all text-violet-200">{claim.recipientWallet}</code></div>{error && <p className="text-rose-300">{error}</p>}<button onClick={verifyWallet} disabled={Boolean(busy)} className="w-full rounded-lg bg-gradient-to-r from-emerald-300 via-cyan-400 to-violet-500 py-3 font-semibold text-slate-950 disabled:opacity-60">{busy === "wallet" ? "Waiting for signature…" : "Sign message and continue"}</button></div>;
  return <div className="rounded-xl border border-emerald-300/20 bg-emerald-300/10 p-5 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-emerald-300"/><h3 className="mt-3 font-semibold text-white">Verification submitted</h3><p className="mt-2 text-sm leading-relaxed text-emerald-100/80">Your verified details will now be reviewed. If everything is correct, your claim will be approved and the handle will be minted directly to the recipient wallet, typically within 24–48 hours.</p></div>;
}

function CopyField({ label, value }) {
  return <div><span className="mb-1 block text-xs text-slate-400">{label}</span><div className="flex items-center gap-2 rounded-lg bg-black/30 p-3"><code className="min-w-0 flex-1 break-all text-cyan-200">{value}</code><button type="button" onClick={() => navigator.clipboard.writeText(value)} aria-label={`Copy ${label}`}><Copy className="h-4 w-4"/></button></div></div>;
}