import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { CheckCircle2, Clock3, ShieldCheck, WalletCards } from "lucide-react";
import { base44 } from "@/api/base44Client";

export default function ReferralExplainer() {
  const [info, setInfo] = useState(null); useEffect(() => { base44.functions.invoke("referralPortal", { action: "program_info" }).then((r) => setInfo(r.data)).catch(() => null); }, []);
  const tiers = info ? [["Starter", `1–${info.tier2Start - 1} mints`, info.tier1], ["Growth", `${info.tier2Start}–${info.tier3Start - 1} mints`, info.tier2], ["Pro", `${info.tier3Start}–${info.tier4Start - 1} mints`, info.tier3], ["Elite", `${info.tier4Start}+ mints`, info.tier4]] : [];
  return <section className="mt-12 space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-violet-300">How rewards work</p><h2 className="mt-2 text-3xl font-semibold">Clear, verifiable and paid in SOL</h2><p className="mt-3 max-w-3xl leading-relaxed text-slate-400">A visitor follows your unique link, claims a SolHandle and completes the mint on Solana. Only after that transaction is confirmed does the reward enter your balance.</p></div>
    <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-4">{tiers.length ? tiers.map(([name, range, rate]) => <div key={name} className="rounded-xl border border-cyan-300/15 bg-cyan-300/5 p-5"><span className="text-sm text-slate-400">{range}</span><b className="mt-2 block text-3xl text-cyan-200">{rate}%</b><span className="text-sm font-semibold text-white">{name} rate</span></div>) : <div className="col-span-full rounded-xl border border-white/10 p-5 text-slate-400">Loading current reward tiers…</div>}</div>
    <div className="grid gap-4 lg:grid-cols-3"><div className="card-glow"><WalletCards className="h-5 w-5 text-emerald-300"/><h3 className="mt-3 font-semibold">What do you earn from?</h3><p className="mt-2 text-sm leading-relaxed text-slate-400">Commission is calculated on eligible mint revenue. {info?.premiumEligible ? "Premium surcharges currently qualify too." : "Premium surcharges are currently excluded."}</p></div><div className="card-glow"><Clock3 className="h-5 w-5 text-cyan-300"/><h3 className="mt-3 font-semibold">When can you withdraw?</h3><p className="mt-2 text-sm leading-relaxed text-slate-400">Rewards become available after a {info?.holdHours ?? "—"}-hour verification hold. The current payout minimum is {info?.minimumPayoutSol ?? "—"} SOL.</p></div><div className="card-glow"><ShieldCheck className="h-5 w-5 text-violet-300"/><h3 className="mt-3 font-semibold">What counts?</h3><p className="mt-2 text-sm leading-relaxed text-slate-400">The referral must be attributed through your link and result in a confirmed mint. Failed transactions and self-referrals earn nothing.</p></div></div>
    <div className="rounded-2xl border border-white/10 bg-white/5 p-6"><h3 className="text-xl font-semibold">Important conditions</h3><div className="mt-4 grid gap-3 text-sm text-slate-300 md:grid-cols-2">{["You need to own a verified SolHandle to activate your link.", `Referral attribution remains valid for ${info?.cookieDays ?? "—"} days.`, "Spam, phishing, impersonation and link manipulation are prohibited.", "Suspicious rewards may be held while activity is reviewed."].map((item) => <p key={item} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300"/>{item}</p>)}</div><Link to="/referral-terms" className="mt-5 inline-block text-sm font-semibold text-cyan-200">Read the complete Share & Earn Terms →</Link></div>
  </section>;
}