import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { CheckCircle2, Clock3, ShieldCheck, WalletCards } from "lucide-react";
import { base44 } from "@/api/base44Client";

export default function ReferralExplainer() {
  const [info, setInfo] = useState(null); useEffect(() => { base44.functions.invoke("referralPortal", { action: "program_info" }).then((r) => setInfo(r.data)).catch(() => null); }, []);
  const features = [[WalletCards, "Handle-based network", "Every confirmed first mint permanently links the referred wallet and asset to your origin handle."], [Clock3, "24-hour tier qualification", `Tier upgrades wait ${info?.qualificationHours ?? 24} hours; token-balance downgrades apply immediately.`], [ShieldCheck, "Actual revenue only", "Secondary and creator-fee shares use revenue SolHandle actually received, never theoretical fees."]];
  return <section className="mt-12 space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-violet-300">Simple by design</p><h2 className="mt-2 text-3xl font-semibold">Refer once. Track the lifecycle.</h2><p className="mt-3 max-w-3xl leading-relaxed text-slate-400">A visitor opens your link and completes a first mint within the {info?.cookieDays ?? 30}-day attribution window. Their wallet and minted asset then keep the same origin referrer across future supported activity.</p></div><div className="grid gap-4 lg:grid-cols-3">{features.map(([Icon, title, text]) => <div key={title} className="card-glow"><Icon className="h-5 w-5 text-cyan-300"/><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-400">{text}</p></div>)}</div><div className="rounded-2xl border border-white/10 bg-white/5 p-6"><h3 className="text-xl font-semibold">Ambassador rules</h3><div className="mt-4 grid gap-3 text-sm text-slate-300 md:grid-cols-2">{["A confirmed SolHandle owned by your connected wallet is required to activate a referral link.", "One wallet receives one permanent origin referrer after its first confirmed mint.", "Self-referrals never qualify and duplicate revenue events are ignored.", "Pre-launch activity is recorded, but it does not accrue claimable earnings."].map((item) => <p key={item} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300"/>{item}</p>)}</div><Link to="/referral-terms" className="mt-5 inline-block text-sm font-semibold text-cyan-200">Read the complete Share & Earn Terms →</Link></div></section>;
}