import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { CheckCircle2, Clock3, ShieldCheck, WalletCards } from "lucide-react";
import { base44 } from "@/api/base44Client";

export default function ReferralExplainer() {
  const [info, setInfo] = useState(null); useEffect(() => { base44.functions.invoke("referralPortal", { action: "program_info" }).then((r) => setInfo(r.data)).catch(() => null); }, []);
  const features = [[WalletCards, "Earn from referral #1", `${info?.commissionPercentage ?? 20}% of every eligible confirmed mint, including Premium surcharge.`], [Clock3, "Verified before payout", `Rewards stay pending for ${info?.holdHours ?? 24} hours, then become available.`], [ShieldCheck, "Real mints only", "No rewards for failed, duplicate, devnet, admin or self-referral transactions."]];
  return <section className="mt-12 space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-violet-300">Simple by design</p><h2 className="mt-2 text-3xl font-semibold">Bring real users. Earn real SOL.</h2><p className="mt-3 max-w-3xl leading-relaxed text-slate-400">A visitor opens your link, searches freely and mints within the {info?.cookieDays ?? 30}-day attribution window. The buyer always pays the normal price; your reward comes from SolHandle revenue after on-chain confirmation.</p></div><div className="grid gap-4 lg:grid-cols-3">{features.map(([Icon, title, text]) => <div key={title} className="card-glow"><Icon className="h-5 w-5 text-cyan-300"/><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-400">{text}</p></div>)}</div><div className="rounded-2xl border border-white/10 bg-white/5 p-6"><h3 className="text-xl font-semibold">Ambassador rules</h3><div className="mt-4 grid gap-3 text-sm text-slate-300 md:grid-cols-2">{["Any connected Solana wallet can participate.", "Existing referral links and historic rewards stay unchanged.", "No buyer discount and no change to the on-chain mint price.", "Suspicious activity is reviewed; IP alone never triggers a ban."].map((item) => <p key={item} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300"/>{item}</p>)}</div><Link to="/referral-terms" className="mt-5 inline-block text-sm font-semibold text-cyan-200">Read the complete Share & Earn Terms →</Link></div></section>;
}