export default function TokenDetectionResult({ result }) {
  const fields = [['Network', 'Mainnet-beta · finalized'], ['Mint address', result.mint], ['Token program', result.program], ['Program address', result.programAddress], ['Decimals', result.decimals], ['Raw supply', result.supplyRaw], ['Mint authority', result.mintAuthority ?? 'Revoked / none'], ['Freeze authority', result.freezeAuthority ?? 'Revoked / none'], ['Mint slot', result.slot], ['Metadata read slot', result.metadataSlot], ['Read time', result.checkedAt], ['Extensions (type IDs)', result.extensionTypes.join(', ') || 'None']];
  return <div className="mt-5 space-y-5" aria-live="polite">
    <div className="rounded-xl border border-names-secondary/30 p-4"><p className="text-xs uppercase tracking-wider text-names-secondary">Detected candidate · not verified</p><h3 className="mt-2 font-mono text-2xl">{result.candidate || 'Manual review required'}</h3><p className="mt-2 text-sm text-muted-foreground">{result.symbolReason || 'Derived from mint-bound metadata. This is not a claim or proof of project ownership.'}</p></div>
    <dl className="space-y-3">{fields.map(([label, value]) => <div key={label} className="grid gap-1 lg:grid-cols-[180px_minmax(0,1fr)]"><dt className="text-sm text-muted-foreground">{label}</dt><dd className="break-all font-mono text-sm">{String(value ?? 'Unavailable')}</dd></div>)}</dl>
    {result.metadata.map(item => <section key={item.source} className="rounded-xl border border-border p-4"><h3 className="font-semibold">{item.source}</h3><dl className="mt-3 space-y-2">{[['Name', item.name], ['Raw symbol', item.symbol], ['Metadata account', item.address], ['Update authority', item.updateAuthority ?? 'Revoked / none'], ['Mutable', item.mutable == null ? 'Not determined' : item.mutable ? 'Yes' : 'No'], ['URI (not fetched)', item.uri]].map(([label, value]) => <div key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="whitespace-pre-wrap break-all text-sm">{value || 'Missing'}</dd></div>)}</dl></section>)}
    {result.pointer && <div className="rounded-xl border border-border p-4"><h3 className="font-semibold">Metadata pointer</h3><p className="mt-2 break-all text-sm">Address: {result.pointer.address || 'None'}</p><p className="mt-2 break-all text-sm">Authority: {result.pointer.authority || 'Revoked / none'}</p></div>}
    <div className="rounded-xl border border-names-warning/30 p-4 text-sm"><h3 className="font-semibold text-names-warning">Protection and conflict checks</h3><p className="mt-2">{result.protection}</p><p className="mt-2 text-muted-foreground">{result.registry}</p><p className="mt-2 text-muted-foreground">{result.conflicts}</p></div>
    {result.warnings.length > 0 && <ul className="list-disc space-y-2 pl-5 text-sm text-names-warning">{result.warnings.map(warning => <li key={warning}>{warning}</li>)}</ul>}
    <a href={`https://solscan.io/token/${result.mint}`} target="_blank" rel="noopener noreferrer" className="inline-block text-sm text-names-accent">View mint on Solscan →</a>
  </div>;
}