import { useState } from "react";
import Header from "@/components/solhandle/Header";

export default function Contact() {
  const requestedHandle = new URLSearchParams(window.location.search).get("handle");
  const [form, setForm] = useState({ name: "", email: "", message: requestedHandle ? `I would like information about the protected brand handle @${requestedHandle}.` : "" });
  const submit = (event) => { event.preventDefault(); const body = `Name: ${form.name}\nEmail: ${form.email}\n\n${form.message}`; const subject = requestedHandle ? `Protected brand information: @${requestedHandle}` : "SolHandle enquiry"; window.location.href = `mailto:info@solhandle.io?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`; };
  return <main className="min-h-screen bg-[#050811] text-white"><div className="mx-auto min-h-screen max-w-7xl border-x border-white/10"><Header/><section className="mx-auto max-w-xl px-5 py-14 md:px-9"><p className="text-sm text-cyan-300">Contact</p><h1 className="mt-2 text-4xl font-semibold">Get in touch</h1><p className="mt-4 leading-relaxed text-slate-400">Send a question or partnership enquiry. The form opens your email app with the details prefilled.</p><form onSubmit={submit} className="card-glow mt-8 space-y-5"><Field label="Name" value={form.name} onChange={name => setForm({ ...form, name })}/><Field label="Email" type="email" value={form.email} onChange={email => setForm({ ...form, email })}/><label className="block text-sm text-slate-300">Message<textarea required rows="5" value={form.message} onChange={e => setForm({ ...form, message: e.target.value })} className="mt-2 w-full rounded-lg border border-white/10 bg-slate-900 p-3 text-white outline-none focus:border-cyan-300"/></label><button className="w-full rounded-lg bg-gradient-to-r from-emerald-300 via-cyan-400 to-violet-500 py-3 font-semibold text-slate-950">Open email message</button></form></section></div></main>;
}
function Field({ label, type = "text", value, onChange }) { return <label className="block text-sm text-slate-300">{label}<input required type={type} value={value} onChange={e => onChange(e.target.value)} className="mt-2 w-full rounded-lg border border-white/10 bg-slate-900 p-3 text-white outline-none focus:border-cyan-300"/></label>; }