import Header from "@/components/solhandle/Header";
import { Link } from 'react-router-dom';
import ResolverDemo from "@/components/solhandle/ResolverDemo";
import DeveloperIntegrationTabs from "@/components/solhandle/DeveloperIntegrationTabs";
import ResolutionStatus from "@/components/solhandle/ResolutionStatus";
import ResolutionGuide from "@/components/solhandle/ResolutionGuide";
import ProtocolPaperCta from "@/components/solhandle/ProtocolPaperCta";
import DevelopersMobileView from '@/components/solhandle/DevelopersMobileView';

export default function Developers() {
  return <main className="min-h-screen bg-[#050811] text-white"><div className="mx-auto min-h-screen max-w-7xl border-x border-white/10"><Header/><section className="px-5 py-6 sm:py-12 md:px-9"><Link to="/developers/partner-mint" className="mb-6 block rounded-xl border border-names-secondary/25 p-4"><span className="text-xs font-semibold uppercase tracking-wider text-names-secondary">Planned · SOL only</span><span className="mt-2 block font-semibold text-names-accent">Partner Mint — Phase 1–3 technical plan →</span><span className="mt-2 block text-sm text-slate-400">Native partner minting, atomic 50/50 revenue sharing, SDK, widget and dashboard. Not live yet.</span></Link><Link to="/developers/token-handles" className="mb-6 block rounded-xl border border-names-accent/25 p-4"><span className="text-xs font-semibold uppercase tracking-wider text-names-secondary">Planned · Claims disabled</span><span className="mt-2 block font-semibold text-names-accent">Verified $ Token Handles — security-first plan →</span><span className="mt-2 block text-sm text-muted-foreground">@ for wallets. $ for tokens. Verified mint bindings, independent dual review and a non-transferable registry. Not live yet.</span></Link><DevelopersMobileView/><div className="hidden sm:block"><p className="text-sm font-medium tracking-wider text-cyan-300">SOLHANDLE RESOLUTION PROTOCOL</p><h1 className="mt-2 max-w-3xl text-4xl font-semibold md:text-5xl">Add SolHandle in minutes.</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-slate-300">Resolve a human-readable Solana identity to its current NFT owner, directly from Solana. SolHandle never holds funds or routes transactions.</p><ProtocolPaperCta/><div className="mt-5 rounded-xl border border-violet-300/20 bg-violet-300/5 p-4 text-sm text-violet-100"><strong>Source of truth:</strong> Solana program → HandleRecord → verified Metaplex Core Asset → current owner. The API is only a convenience layer.</div><ResolutionGuide/><ResolverDemo/><DeveloperIntegrationTabs/><ResolutionStatus/><section className="mt-12 border-t border-white/10 pt-8"><h2 className="text-2xl font-semibold">Security rule for native SOL</h2><p className="mt-3 max-w-3xl leading-relaxed text-slate-400">A verified handle is not automatically a safe payment destination. Integrations must also confirm that the current owner is a System Program wallet or an unfunded on-curve address. Program-owned accounts and PDAs are blocked by the resolver’s safety result.</p></section></div></section></div></main>;
}