import Header from "@/components/solhandle/Header";

const sections = [
  { id: "overview", title: "What is SolHandle?", content: <p>SolHandle gives a Solana wallet a unique, human-readable <strong className="text-white">@handle</strong>. Each handle is minted as an NFT in the official SolHandle collection. Ownership lives in the holder’s wallet: the blockchain is the source of truth, while SolHandle’s index makes search and display fast.</p> },
  { id: "rules", title: "Handle rules", content: <p>Handles are 1–20 characters long and can use lowercase letters and numbers. They are normalized to lowercase, so <strong className="text-white">@Ansem</strong> and <strong className="text-white">@ansem</strong> are the same handle. Every handle maps to a deterministic registry record and asset address, which prevents duplicates.</p> },
  { id: "minting", title: "How minting works", content: <ol className="list-decimal space-y-2 pl-5"><li>Search checks the indexed registry and protected-name list.</li><li>The protocol calculates the tier price and the wallet sets a maximum accepted price.</li><li>One atomic transaction transfers the mint fee and creates the official collection asset.</li><li>The resulting NFT is owned directly by the minting wallet.</li></ol> },
  { id: "pricing", title: "Mint pricing", content: <div className="overflow-hidden rounded-xl border border-white/10"><table className="w-full text-left text-sm"><thead className="bg-white/5 text-slate-300"><tr><th className="px-4 py-3">Tier</th><th className="px-4 py-3">Length</th><th className="px-4 py-3">Mint</th></tr></thead><tbody className="divide-y divide-white/10 text-slate-400"><tr><td className="px-4 py-3 text-white">Ultra Rare</td><td className="px-4 py-3">1</td><td className="px-4 py-3">2 SOL</td></tr><tr><td className="px-4 py-3 text-white">Very Rare</td><td className="px-4 py-3">2</td><td className="px-4 py-3">1 SOL</td></tr><tr><td className="px-4 py-3 text-white">Rare</td><td className="px-4 py-3">3</td><td className="px-4 py-3">0.50 SOL</td></tr><tr><td className="px-4 py-3 text-white">Short</td><td className="px-4 py-3">4</td><td className="px-4 py-3">0.20 SOL</td></tr><tr><td className="px-4 py-3 text-white">Standard</td><td className="px-4 py-3">5–20</td><td className="px-4 py-3">0.10 SOL</td></tr></tbody></table></div> },
  { id: "ownership", title: "Ownership, transfers & primary handles", content: <p>The current owner of the official NFT owns the handle. Handles can be transferred through compatible marketplaces or wallet transfers without SolHandle taking custody. A holder can designate one owned handle as their primary handle; the protocol verifies NFT ownership before that record is updated.</p> },
  { id: "protected", title: "Protected handles", content: <p>Protocol names, strategic names, verified claims and protected brands may be reserved. A reserved handle cannot be minted until it is explicitly released. The protected-name index improves the search experience, while the on-chain reservation is the final enforcement point.</p> },
  { id: "economics", title: "Payments & royalties", content: <p>Primary mint revenue is sent to the protocol treasury in the mint transaction. The official collection carries a 5% secondary-market royalty, allocated to the Integration Rewards Vault. SolHandle does not require renewals or recurring subscription payments for a minted handle.</p> },
  { id: "security", title: "Security model", content: <p>SolHandle is non-custodial: no private keys, seed phrases or NFTs are held by the website. Minting checks handle validity, protocol pause status, reservations, collection identity, price limits and deterministic addresses. Always confirm the transaction details in your wallet before signing.</p> },
  { id: "api", title: "Index & developer access", content: <p>The public application index supports handle availability, recent handles, protocol statistics and handles owned by a wallet. The on-chain program remains authoritative; index data may be refreshed after chain activity. Full SDK examples, live program addresses and the official collection address will be published after Devnet deployment.</p> },
];

export default function Docs() {
  return <main className="min-h-screen bg-[#050811] text-white"><div className="mx-auto min-h-screen max-w-7xl border-x border-white/10"><Header/><section className="grid gap-10 px-5 py-12 md:grid-cols-[220px_1fr] md:px-9"><aside className="space-y-3 md:sticky md:top-6 md:h-fit">{sections.map(({ id, title }) => <a href={`#${id}`} key={id} className="block text-sm text-slate-400 hover:text-cyan-200">{title}</a>)}</aside><article className="max-w-3xl"><p className="text-sm text-cyan-300">Documentation</p><h1 className="mt-2 text-4xl font-semibold">Your @ on Solana.</h1><p className="mt-5 text-lg leading-relaxed text-slate-300">The protocol documentation for SolHandle’s ownership, pricing and registry rules.</p><div className="mt-6 rounded-xl border border-cyan-300/20 bg-cyan-300/5 p-4 text-sm leading-relaxed text-cyan-100"><strong>Deployment status:</strong> protocol rules and pricing are defined. Live Devnet addresses, collection details and developer transaction examples will follow after deployment.</div>{sections.map(({ id, title, content }) => <section id={id} key={id} className="mt-10 border-t border-white/10 pt-7"><h2 className="text-xl font-semibold">{title}</h2><div className="mt-3 leading-relaxed text-slate-400">{content}</div></section>)}</article></section></div></main>;
}