import Header from "@/components/solhandle/Header";

const Address = ({ children }) => <code className="break-all text-cyan-200">{children}</code>;

const sections = [
  { id: "overview", title: "What is SolHandle?", content: <p>SolHandle is a live, non-custodial identity protocol on Solana Mainnet Beta. It gives a wallet a unique, human-readable <strong className="text-white">@handle</strong>, represented by a Metaplex Core NFT in the official SolHandle collection. The wallet holding that asset controls the identity.</p> },
  { id: "network", title: "Mainnet deployment", content: <div className="space-y-3"><p>Protocol V2 is deployed and active on Solana Mainnet Beta. Mainnet and Mainnet Beta refer to the same live production network: transactions use real SOL and create permanent on-chain state.</p><ul className="space-y-2"><li><strong className="text-white">Program:</strong> <Address>B7xiwfxGcR2Xz7tcUKrkB8Ly6NV8jU7LH1m6GJZRUuf</Address></li><li><strong className="text-white">Official collection:</strong> <Address>7XZzcbeFBxQA63n9avz44vnbpv34hDGYyHfCDmTdPBJP</Address></li><li><strong className="text-white">Treasury:</strong> <Address>CZvu8vnzLKyfGmbpixypQcfW4iiw7em43utW4k6ordYP</Address></li><li><strong className="text-white">Integration Rewards Vault:</strong> <Address>FANW54mUan9Gnj7qAy8qcVUTJxD8eZgtXpTkDbzg9wtc</Address></li></ul></div> },
  { id: "truth", title: "Source of truth", content: <p>The authority order is <strong className="text-white">Solana blockchain → indexer → database/cache → interface</strong>. Deterministic on-chain records, the official collection asset and its current owner are authoritative. SolHandle’s index and API improve speed and discovery but never replace or override chain state.</p> },
  { id: "rules", title: "Handle rules", content: <p>Handles are 1–20 characters long and contain lowercase letters and numbers only. Input is normalized to lowercase, so <strong className="text-white">@Ansem</strong> and <strong className="text-white">@ansem</strong> identify the same handle. Deterministic Handle and Asset addresses enforce uniqueness on-chain.</p> },
  { id: "availability", title: "Search, availability & reservations", content: <p>Search uses the index for a fast result and checks protected-name policy. Final availability is enforced by the Mainnet program when the transaction executes. Existing Handle records, active on-chain reservations and protocol rules prevent duplicate or unauthorized mints.</p> },
  { id: "minting", title: "How minting works", content: <ol className="list-decimal space-y-2 pl-5"><li>Search returns the handle’s availability, rarity and current protocol price.</li><li>The wallet prepares a Mainnet transaction with a maximum accepted price.</li><li>One atomic transaction validates the name and reservation, transfers the fee and creates the official collection asset.</li><li>The NFT is minted directly to the claimant’s wallet; SolHandle never takes custody.</li><li>After confirmation, the index synchronizes the new on-chain record for search and discovery.</li></ol> },
  { id: "pricing", title: "Mainnet mint pricing", content: <div className="space-y-3"><div className="overflow-hidden rounded-xl border border-white/10"><table className="w-full text-left text-sm"><thead className="bg-white/5 text-slate-300"><tr><th className="px-4 py-3">Tier</th><th className="px-4 py-3">Length</th><th className="px-4 py-3">Mint</th></tr></thead><tbody className="divide-y divide-white/10 text-slate-400"><tr><td className="px-4 py-3 text-white">Legendary</td><td className="px-4 py-3">1</td><td className="px-4 py-3">3 SOL</td></tr><tr><td className="px-4 py-3 text-white">Ultra Rare</td><td className="px-4 py-3">2</td><td className="px-4 py-3">2 SOL</td></tr><tr><td className="px-4 py-3 text-white">Rare</td><td className="px-4 py-3">3</td><td className="px-4 py-3">1 SOL</td></tr><tr><td className="px-4 py-3 text-white">Uncommon</td><td className="px-4 py-3">4</td><td className="px-4 py-3">0.5 SOL</td></tr><tr><td className="px-4 py-3 text-white">Standard</td><td className="px-4 py-3">5–20</td><td className="px-4 py-3">0.1 SOL</td></tr></tbody></table></div><div className="rounded-xl border border-violet-300/25 bg-violet-400/10 p-4"><p className="font-semibold text-violet-100">Premium handles include a fixed +1 SOL surcharge.</p><p className="mt-2">The official Premium database contains 2,500 curated names. Their final mint price is always <strong className="text-white">base price + 1 SOL</strong>. For example, <strong className="text-white">@travel</strong> has a 0.1 SOL base price and a 1 SOL Premium surcharge, for a total of <strong className="text-white">1.1 SOL</strong>.</p></div><p>The search result and checkout show the Premium label, base price, surcharge and final total before signing. The server independently recalculates and validates the required payment. Network transaction fees are separate.</p></div> },
  { id: "ownership", title: "Ownership, transfers & Primary Handle", content: <p>The current owner of the verified official NFT owns the handle. It can be transferred with a compatible wallet or external marketplace without SolHandle acting as custodian or escrow. A wallet may set one owned identity as its Primary Handle for verified reverse resolution; the protocol checks current NFT ownership before updating that record.</p> },
  { id: "resolution", title: "Forward and reverse resolution", content: <div className="space-y-3"><p>Forward resolution maps <strong className="text-white">@handle → current verified NFT owner</strong>. Reverse resolution maps <strong className="text-white">wallet → @handle</strong> only when that wallet set a Primary Handle and still owns its official asset.</p><p>Integrations must verify the SolHandle program, deterministic record, official collection and current asset owner. For native SOL, they must also require a safe wallet destination and display the resolved base58 address before approval.</p></div> },
  { id: "protected", title: "Protected handles & official claims", content: <p>Protocol names, strategic names and recognizable organizations may be reserved on-chain to prevent impersonation. A reserved handle is not owned or minted by SolHandle. After domain, wallet and any required known-channel verification, it is minted directly and free of charge to the official organization’s specified wallet. Once minted, the directory marks it as officially claimed and it cannot be requested again.</p> },
  { id: "market", title: "Transfers and market discovery", content: <p>SolHandle may surface verified listings from external marketplaces as a discovery layer. Sales, settlement and custody remain with the external marketplace and participating wallets; SolHandle does not operate an internal marketplace or escrow service.</p> },
  { id: "economics", title: "Payments, royalties & renewals", content: <p>Primary mint revenue is transferred to the protocol treasury inside the atomic mint transaction. The official collection carries a 5% secondary-market royalty supporting the SolHandle treasury and Integration Rewards Vault according to the collection configuration. Minted handles have no recurring SolHandle renewal fee or subscription.</p> },
  { id: "security", title: "Security model", content: <div className="space-y-3"><p>SolHandle never asks for or stores private keys or seed phrases and never holds user NFTs. The Mainnet program validates format, uniqueness, deterministic addresses, protocol version and pause state, reservations, collection identity and accepted price.</p><p>Users should verify the handle, price, recipient, program and network in their wallet before signing. Mainnet transactions use real SOL and cannot be reversed by SolHandle.</p></div> },
  { id: "developers", title: "Developer access", content: <div className="space-y-3"><p>Install the public <strong className="text-white">solhandle-sdk</strong> package for authoritative resolution directly from Solana RPC state. The forward and reverse REST endpoints remain available as a non-authoritative convenience layer.</p><pre className="overflow-x-auto rounded-xl bg-black/40 p-4 text-sm text-cyan-100"><code>npm install solhandle-sdk @solana/web3.js</code></pre><p>Native third-party wallet integrations remain unverified until their implementations pass the Mainnet test suite. See the <a href="/developers" className="text-cyan-200">Developer page</a> for working examples and security rules.</p></div> },
];

export default function Docs() {
  return <main className="min-h-screen bg-[#050811] text-white"><div className="mx-auto min-h-screen max-w-7xl border-x border-white/10"><Header/><section className="grid gap-10 px-5 py-12 md:grid-cols-[220px_1fr] md:px-9"><aside className="space-y-3 md:sticky md:top-6 md:h-fit">{sections.map(({ id, title }) => <a href={`#${id}`} key={id} className="block text-sm text-slate-400 hover:text-cyan-200">{title}</a>)}</aside><article className="max-w-3xl"><p className="text-sm text-cyan-300">Documentation</p><h1 className="mt-2 text-4xl font-semibold">Your @ on Solana.</h1><p className="mt-5 text-lg leading-relaxed text-slate-300">The protocol documentation for SolHandle’s ownership, pricing and registry rules.</p><div className="mt-6 rounded-xl border border-emerald-300/20 bg-emerald-300/5 p-4 text-sm leading-relaxed text-emerald-100"><strong>Mainnet status:</strong> Protocol V2 is live and unpaused on Solana Mainnet Beta. Minting, protected official claims, direct forward resolution, verified Primary Handle reverse resolution and native-SOL destination classification use the production deployment. The public solhandle-sdk package is live under the MIT License; native third-party wallet integrations are listed as unverified until they pass the Mainnet test suite.</div>{sections.map(({ id, title, content }) => <section id={id} key={id} className="mt-10 border-t border-white/10 pt-7"><h2 className="text-xl font-semibold">{title}</h2><div className="mt-3 leading-relaxed text-slate-400">{content}</div></section>)}</article></section></div></main>;
}