import { useEffect, useState } from "react";
import { Search } from "lucide-react";
import { base44 } from "@/api/base44Client";
import Header from "@/components/solhandle/Header";
import ExploreFilters from "@/components/solhandle/ExploreFilters";
import ExploreHandleCard from "@/components/solhandle/ExploreHandleCard";

const tabs = [["all", "All"], ["recent", "Recently Claimed"], ["premium", "Premium"], ["short", "Short Handles"]];
const initialFilters = { rarity: "", characterType: "", sort: "newest" };

export default function Explore() {
  const [tab, setTab] = useState("all"); const [search, setSearch] = useState(""); const [filters, setFilters] = useState(initialFilters);
  const [page, setPage] = useState(1); const [result, setResult] = useState({ handles: [], hasMore: false }); const [loading, setLoading] = useState(true);
  useEffect(() => { const timer = setTimeout(() => { setLoading(true); base44.functions.invoke("getExploreHandles", { tab, search, page, ...filters }).then((res) => setResult(res.data)).finally(() => setLoading(false)); }, 250); return () => clearTimeout(timer); }, [tab, search, page, filters]);
  const updateTab = (value) => { setTab(value); setPage(1); if (value === "short" && filters.rarity === "STANDARD") setFilters({ ...filters, rarity: "" }); }; const updateFilters = (value) => { setFilters(value); setPage(1); if (tab === "short" && value.rarity === "STANDARD") setTab("all"); };
  return <main className="min-h-screen bg-[#050811] text-white"><div className="mx-auto min-h-screen max-w-7xl border-x border-white/10"><Header/><section className="px-5 py-12 md:px-9"><p className="text-sm font-medium tracking-wider text-cyan-300">EXPLORE SOLHANDLES</p><h1 className="mt-2 text-4xl font-semibold">Discover identities claimed on Solana.</h1><div className="relative mt-7"><Search className="absolute left-4 top-3.5 h-5 w-5 text-slate-500"/><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Search @handle..." className="w-full rounded-xl border border-white/10 bg-slate-950/70 py-3 pl-12 pr-4 text-white outline-none focus:border-cyan-300/50"/></div><div className="my-5 flex flex-wrap gap-2">{tabs.map(([value, label]) => <button key={value} onClick={() => updateTab(value)} className={`rounded-full px-4 py-2 text-sm ${tab === value ? "bg-cyan-300 text-slate-950" : "border border-white/10 text-slate-300"}`}>{label}</button>)}</div><ExploreFilters filters={filters} onChange={updateFilters}/>{loading ? <div className="card-glow mt-8 text-slate-400">Loading SolHandles…</div> : result.handles.length ? <div className="mt-8 grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-4">{result.handles.map((item) => <ExploreHandleCard key={item.asset || item.handle} item={item}/>)}</div> : <div className="card-glow mt-8 text-center text-slate-400">No SolHandles match these filters.</div>}<div className="mt-8 flex justify-center gap-3"><button disabled={page === 1} onClick={() => setPage(page - 1)} className="rounded-lg border border-white/10 px-4 py-2 text-sm disabled:opacity-40">Previous</button><span className="px-3 py-2 text-sm text-slate-400">Page {page}</span><button disabled={!result.hasMore} onClick={() => setPage(page + 1)} className="rounded-lg border border-white/10 px-4 py-2 text-sm disabled:opacity-40">Next</button></div></section></div></main>;
}