import { Link } from 'react-router-dom';
const rules = [
  ['Pilot, geen tokenbelofte', 'Deze eerste fase kent pilot-XP toe voor profiel- en kennisquests. Reward-eligible XP blijft nul. Er zijn geen definitieve $HANDLE-allocaties of uitbetalingen. Het Genesis-budget is uitsluitend een voorstel.'],
  ['Echte verificatie', 'Een walletconnectie of klik alleen levert geen XP op. De server controleert je walletsignature en geregistreerde profiel of alle quizantwoorden. Quests zijn eenmalig per wallet en lifetime; herhaalde aanvragen tellen niet opnieuw mee in XP-totalen.'],
  ['Seizoenen en levels', 'Lifetime XP blijft behouden. Alleen nieuwe credits tijdens een actief seizoen tellen als season XP. Credits vóór de start of na de eindtijd tellen niet retroactief mee. Levels: Newcomer 0, Explorer 500, Supporter 1.500, Ambassador 4.000 en Legend 10.000 XP.'],
  ['Regelwijzigingen', 'Beheer moet een quest pauzeren voordat de volgende versie wordt opgeslagen. Je inzending vermeldt de versie; gewijzigde regels vereisen opnieuw openen van de quest. Eerder verdiende XP wordt niet overschreven.'],
  ['Privacy en walletverificatie', 'Je profiel is standaard niet zichtbaar op de ranglijst. Publieke deelname is optioneel. De Growth Hub bewaart geen private keys. Een ondertekende nonce is maximaal 15 minuten geldig voor je Growth Hub-activiteiten, zonder toegang tot geld.'],
  ['Geen engagementfarm', 'Betaalde likes, reposts en follows behoren niet tot dit programma. Originele tutorials, bugrapporten en integraties kunnen pas in een latere fase na kwaliteitsreview worden beloond.'],
  ['Productiegrens', 'Deze core pilot is geen financieel rewardsysteem. De bestaande datalaag heeft geen unieke databaseconstraints of gedocumenteerde multi-recordtransacties. Canonieke completiongroepen voorkomen dubbele XP in getoonde totalen; gelijktijdige verwerking kan nog dubbele historieboekingen maken. Productie-uitbetalingen blijven geblokkeerd totdat atomaire verwerking, anti-Sybil, auditvolledigheid en reconciliatie aantoonbaar zijn opgelost.'],
  ['Volgende fasen', 'On-chain mint- en Pay-verificatie, Watchlist, referralconversies, handmatige review, meerdere gekoppelde wallets, rewardallocaties en $HANDLE-uitbetalingen zijn nog niet actief. Bestaande mint-, Pay- en Share & Earn-processen worden niet aangepast.'],
  ['Vragen of bezwaar', 'Bij onjuiste XP of profielblokkering kun je contact opnemen met SolHandle. Vermeld je wallet, quest en tijdstip. Deel nooit je seed phrase. Een automatische blokkering is geen definitief fraudebewijs.']
];
export default function GrowthHubRules() {
  return <><h1>Regels & FAQ</h1><p className="mt-4 text-muted-foreground">Core pilot · regels versie 1 · 9 oktober 2026</p><div className="mt-7 space-y-4">{rules.map(([title, text]) => <section key={title} className="rounded-2xl border border-border bg-card p-6"><h2 className="text-lg font-semibold">{title}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{text}</p></section>)}</div><div className="mt-6 flex flex-wrap gap-5 text-sm text-names-accent"><Link to="/privacy">Privacybeleid</Link><Link to="/legal">Juridische informatie</Link><Link to="/contact">Contact & bezwaar</Link><Link to="/referral-terms">Share & Earn-voorwaarden</Link></div></>;
}