import { Link } from 'react-router-dom';
const rules = [
  ['Pilot, geen tokenbelofte', 'Deze pilot kent XP toe voor profiel- en kennisquests en voor bewezen nieuwe mints en SolHandle Pay-betalingen. Reward-eligible XP blijft nul. Er zijn geen definitieve $HANDLE-allocaties of uitbetalingen. Het Genesis-budget is uitsluitend een voorstel.'],
  ['Echte verificatie', 'Een walletconnectie of klik alleen levert geen XP op. De server controleert je walletsignature en geregistreerde profiel, alle quizantwoorden of finalized on-chain transactiegegevens. Bij mints controleert hij het officiële programma, de collectie en oorspronkelijke minter; een marketplace-aankoop of NFT-overdracht telt niet mee. Een $HANDLE-mint vereist ook bewijs van de officiële tokenbetaling en 50/50 burn/treasuryverdeling. Quests zijn eenmalig per wallet en lifetime; herhaalde aanvragen tellen niet opnieuw mee in XP-totalen.'],
  ['On-chain voorwaarden', 'Alleen Mainnet-beta en succesvolle finalized transacties tellen. Zonder retroactieve toestemming moet de actie na je Growth Hub-aanmelding en questpublicatie zijn uitgevoerd. Plak je transactiehandtekening in de quest; ontbrekend, mislukt of verkeerd bewijs geeft geen XP. De Pay-quest vereist een opgeslagen SolHandle Pay-betaling naar een andere wallet boven het gepubliceerde minimum, standaard 0,01 SOL. Een handtekening kan niet opnieuw voor een andere betaalquest worden gebruikt. Dezelfde geldige $HANDLE-mint mag de algemene mintquest én de $HANDLE-mintquest afronden, elk eenmalig. Bestaande signalen voor verwante wallets worden meegenomen in de fraudereview; automatische detectie van alle betalingen tussen eigen wallets is niet gegarandeerd.'],
  ['Referrals & fraudereview', 'Gebruik je bestaande Share & Earn-profiel en dien de mint-handtekening van je referral in. De server controleert de vastgelegde conversie, oorspronkelijke referral, mintregistratie, koper, officiële collectie en finalized Mainnet-mint. Alleen de eerste vastgelegde referral-mint van een andere wallet na jouw aanmelding en questpublicatie telt, eenmalig. Alle geldige referral-inzendingen en andere inzendingen met open fraudeflags gaan naar beheer; er wordt tot goedkeuring geen XP toegekend. Goedkeuring verifieert het bewijs opnieuw; afwijzing geeft geen XP. Interne reviewdetails zijn alleen voor beheerders. Je eigen reviewstatus kun je vernieuwen in de quest.'],
  ['Profielholds & bezwaar', 'Beheer kan een Growth Hub-profiel met een vastgelegde reden op hold zetten en vrijgeven. Een hold stopt nieuwe quest-XP en verbergt het profiel op de ranglijst; bestaande XP wordt niet verwijderd. Bestaande blokkerende referral-fraudeflags moeten eerst worden opgelost en worden niet door een questbesluit gewist. Een signaal is geen bewijs dat meerdere wallets van dezelfde persoon zijn; beheer beoordeelt dit. Afgewezen reviews kunnen na bezwaar worden heropend. Besluiten worden geaudit, zonder toegang tot wallettegoeden of wijziging van Share & Earn-commissies.'],
  ['Seizoenen en levels', 'Lifetime XP blijft behouden. Alleen nieuwe credits tijdens een actief seizoen tellen als season XP. Credits vóór de start of na de eindtijd tellen niet retroactief mee. Levels: Newcomer 0, Explorer 500, Supporter 1.500, Ambassador 4.000 en Legend 10.000 XP.'],
  ['Regelwijzigingen', 'Beheer moet een quest pauzeren voordat de volgende versie wordt opgeslagen. Je inzending vermeldt de versie; gewijzigde regels vereisen opnieuw openen van de quest. Eerder verdiende XP wordt niet overschreven.'],
  ['Privacy en walletverificatie', 'Je profiel is standaard niet zichtbaar op de ranglijst. Publieke deelname is optioneel. De Growth Hub bewaart geen private keys. Een ondertekende nonce is maximaal 15 minuten geldig voor je Growth Hub-activiteiten, zonder toegang tot geld.'],
  ['Geen engagementfarm', 'Betaalde likes, reposts en follows behoren niet tot dit programma. Originele tutorials, bugrapporten en integraties kunnen pas in een latere fase na kwaliteitsreview worden beloond.'],
  ['Productiegrens', 'Deze core pilot is geen financieel rewardsysteem. De bestaande datalaag heeft geen unieke databaseconstraints of gedocumenteerde multi-recordtransacties. Canonieke completiongroepen voorkomen dubbele XP in getoonde totalen; gelijktijdige verwerking kan nog dubbele historieboekingen maken. Productie-uitbetalingen blijven geblokkeerd totdat atomaire verwerking, anti-Sybil, auditvolledigheid en reconciliatie aantoonbaar zijn opgelost.'],
  ['Volgende fasen', 'Watchlist, cryptografisch gekoppelde extra wallets, rewardallocaties en $HANDLE-uitbetalingen zijn nog niet actief. Bestaande mint-, Pay- en Share & Earn-processen worden niet aangepast.'],
  ['Vragen of bezwaar', 'Bij onjuiste XP of profielblokkering kun je contact opnemen met SolHandle. Vermeld je wallet, quest en tijdstip. Deel nooit je seed phrase. Een automatische blokkering is geen definitief fraudebewijs.']
];
export default function GrowthHubRules() {
  return <><h1>Regels & FAQ</h1><p className="mt-4 text-muted-foreground">Core pilot · regels versie 1 · 9 oktober 2026</p><div className="mt-7 space-y-4">{rules.map(([title, text]) => <section key={title} className="rounded-2xl border border-border bg-card p-6"><h2 className="text-lg font-semibold">{title}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{text}</p></section>)}</div><div className="mt-6 flex flex-wrap gap-5 text-sm text-names-accent"><Link to="/privacy">Privacybeleid</Link><Link to="/legal">Juridische informatie</Link><Link to="/contact">Contact & bezwaar</Link><Link to="/referral-terms">Share & Earn-voorwaarden</Link></div></>;
}