import { useEffect, useState } from 'react';
import Header from '@/components/solhandle/Header';
import GrowthMeter from '@/components/solhandle/GrowthMeter';
import GrowthMilestones from '@/components/solhandle/GrowthMilestones';
import { base44 } from '@/api/base44Client';
export default function Growth() {
  const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { let active = true; base44.functions.invoke('growthCurve', { action: 'view' }).then(r => { if (active) setData(r.data); }).catch(() => { if (active) setError('Growth data is temporarily unavailable.'); }); return () => { active = false; }; }, []);
  const c = data?.cycle; const handles = c ? Math.min(100, Math.floor(Math.max(0, c.handles_now - c.handles_start) / c.handles_target * 100)) : 0; const holders = c ? Math.min(100, Math.floor(Math.max(0, c.holders_now - c.holders_start) / c.holders_target * 100)) : 0; const progress = Math.floor((handles + holders) / 2);
  return <main className="min-h-screen bg-slate-950 text-white"><div className="mx-auto min-h-screen max-w-7xl border-x border-white/10"><Header/><section className="mx-auto max-w-5xl px-5 py-12 sm:py-20"><p className="text-xs font-semibold uppercase tracking-widest text-cyan-300">Handle milestones</p><h1 className="mt-3 text-4xl font-semibold sm:text-5xl">$HANDLE × SolHandle Growth Curve</h1><p className="mt-3 text-slate-400">Every handle matters. Every holder matters. Every milestone moves the ecosystem forward.</p>{error ? <div role="alert" className="mt-10 text-rose-300">{error}</div> : !data ? <p className="mt-10 text-cyan-200">Loading verified progress…</p> : !c ? <div className="mt-10 rounded-2xl border border-white/10 bg-slate-900/60 p-6 text-slate-300">The first cycle is awaiting a verified mainnet holder snapshot. No progress or reward is claimed until measurement begins.</div> : <><div className="mt-10 rounded-2xl border border-cyan-300/25 bg-slate-900/70 p-6"><div className="flex items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-cyan-300">Cycle {c.cycle_number} · {c.cycle_number === 1 ? 'Early adoption' : 'Community growth'}</p><p className="mt-3 text-5xl font-semibold">{progress}% <span className="text-lg text-slate-400">complete</span></p></div><span className="text-sm text-slate-400">Next milestone: {Math.min(100, Math.floor(progress / 10) * 10 + 10)}%</span></div><div role="progressbar" aria-label="Overall growth" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress} className="mt-6 h-3 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-emerald-300 via-cyan-300 to-violet-400" style={{ width: `${progress}%` }}/></div></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><GrowthMeter label="SolHandle adoption" current={c.handles_now} baseline={c.handles_start} target={c.handles_target} percentage={handles}/><GrowthMeter label="$HANDLE qualified holders" current={c.holders_now} baseline={c.holders_start} target={c.holders_target} percentage={holders}/></div><p className="mt-4 text-xs leading-relaxed text-slate-400">50% paid, confirmed mainnet mints · 50% wallets holding at least {data.minimum_balance.toLocaleString()} $HANDLE continuously across hourly snapshots for 24 hours. Net growth since {new Date(c.started_at).toLocaleDateString()}. Last checked {new Date(c.last_checked_at).toLocaleString()}.</p><GrowthMilestones progress={c.max_progress || progress} cycle={c.cycle_number}/>{data.completed_cycles?.length > 0 && <div className="mt-10 border-t border-white/10 pt-6"><h2 className="text-lg font-semibold">Completed cycles</h2><p className="mt-2 text-sm text-slate-400">{data.completed_cycles.map(item => `Cycle ${item.cycle_number}`).join(' · ')} · completion does not imply reward delivery.</p></div>}</>}</section></div></main>;
}