import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import Header from '@/components/solhandle/Header';
import WeekendProofTable from '@/components/solhandle/weekend/WeekendProofTable';
import WeekendMilestones from '@/components/solhandle/weekend/WeekendMilestones';
import WeekendSettlementAccess from '@/components/solhandle/weekend/WeekendSettlementAccess';
import WeekendWinnerAtto from '@/components/solhandle/weekend/WeekendWinnerAtto';
import WeekendRules from '@/components/solhandle/weekend/WeekendRules';
export default function MintWeekend() {
  const query = useQuery({ queryKey: ['mint-weekend'], queryFn: async () => (await base44.functions.invoke('weekendMintRead', {})).data, refetchInterval: 60000, retry: false });
  const data = query.data;
  return <main className="dark min-h-screen bg-background text-foreground"><div className="mx-auto max-w-7xl border-x border-border"><Header/><div className="mx-auto max-w-6xl space-y-5 px-4 py-6 lg:space-y-7 lg:px-9 lg:py-10"><Link to="/" className="text-sm text-names-accent">← Back to home</Link><section className="grid items-center gap-3 lg:gap-6 lg:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)]"><div className="min-w-0"><p className="text-sm font-semibold uppercase tracking-widest text-names-secondary">SolHandle Mint Weekend</p><h1 className="mt-3 text-3xl font-semibold leading-tight lg:text-5xl">Mint an @ on Solana.<br/>Get 100,000 $HANDLE.</h1><p className="mt-3 text-base text-muted-foreground lg:mt-4 lg:text-lg">Only 25 unique wallets. First come, first served. One reward per wallet.</p><p className="mt-2 text-sm text-muted-foreground">3 October 2026 00:00 – 6 October 2026 00:00 · Europe/Berlin (UTC+2) · Extended by 24 hours</p><Link to="/search" className="mt-4 inline-flex min-h-12 w-full items-center justify-center rounded-lg bg-names-accent px-4 py-3 text-sm font-semibold text-background lg:mt-5 lg:w-auto lg:px-5 lg:text-base">Find and mint your @handle</Link></div><WeekendWinnerAtto/></section>{query.isLoading ? <p role="status">Loading verified mint proofs…</p> : query.isError ? <div role="alert"><p>Unable to load campaign proofs. No unverified totals are shown.</p><button onClick={() => query.refetch()} className="mt-2 text-names-accent">Try again</button></div> : data && <><WeekendSettlementAccess data={data} refresh={query.refetch}/><section className="rounded-2xl border border-names-accent/30 bg-card p-4 lg:p-5"><div className="grid grid-cols-2 gap-4 text-sm lg:grid-cols-3 lg:text-base"><div><b className="text-3xl">{data.mintCount}</b><p className="text-muted-foreground">Verified weekend mints</p></div><div><b className="text-3xl">{Math.max(0,25-data.winners.length)} / 25</b><p className="text-muted-foreground">Reward spots remaining</p></div><div className="col-span-2 border-t border-border pt-3 lg:col-span-1 lg:border-0 lg:pt-0"><b className="text-3xl">2.5M</b><p className="text-muted-foreground">$HANDLE reward pool</p></div></div><p className="mt-4 text-sm text-muted-foreground">{data.scan?.final ? 'All weekend mints have been checked. The results are final.' : data.scan?.complete ? 'Mint records are up to date. Results may change until the final check after the weekend.' : 'We are checking the weekend mints. The totals and remaining spots may still change.'} Last updated: {data.scan?.checked_at ? new Date(data.scan.checked_at).toLocaleString('en-GB', { timeZone: 'Europe/Berlin' }) + ' Berlin' : 'Waiting for first scan'}.</p>{data.scan?.error && <p className="mt-2 text-names-warning">{data.scan.error}</p>}</section><WeekendMilestones data={data}/><WeekendProofTable data={data}/><WeekendRules/></>}</div></div></main>;
}