import { ArrowRight, CheckCircle2, Copy, ExternalLink, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import Header from "@/components/solhandle/Header";
import { shortenAddress } from "@/lib/solhandle";
import SimilarHandles from "@/components/solhandle/SimilarHandles";

export default function MintSuccess() {
  const params = new URLSearchParams(window.location.search);
  const handle = String(params.get("handle") || "").replace(/^@/, "");
  const signature = params.get("signature") || "";
  const asset = params.get("asset") || "";
  const wallet = params.get("wallet") || "";
  const explorerUrl = signature ? `https://explorer.solana.com/tx/${signature}?cluster=mainnet-beta` : "";

  if (!handle || !signature) return <main className="min-h-screen bg-[#050811] text-white"><Header/><div className="mx-auto max-w-xl px-5 py-24 text-center"><h1 className="text-3xl font-semibold">Mint details unavailable</h1><p className="mt-3 text-slate-400">Return to search to view or claim a SolHandle.</p><Link to="/" className="mt-7 inline-flex rounded-lg bg-cyan-300 px-5 py-3 font-semibold text-slate-950">Return to search</Link></div></main>;

  return <main className="min-h-screen bg-[#050811] text-white"><div className="mx-auto min-h-screen max-w-7xl border-x border-white/10"><Header/><section className="mx-auto max-w-3xl px-5 py-16 text-center md:py-24"><CheckCircle2 className="mx-auto h-16 w-16 text-emerald-300"/><p className="mt-6 text-sm font-semibold uppercase tracking-[0.22em] text-cyan-300">Mint successful</p><h1 className="mt-3 text-4xl font-semibold sm:text-6xl">@{handle} is yours.</h1><p className="mx-auto mt-5 max-w-xl text-lg text-slate-400">Your SolHandle was successfully minted as an NFT and delivered directly to your connected wallet.</p><div className="mt-10 rounded-2xl border border-cyan-300/25 bg-gradient-to-br from-cyan-300/10 via-slate-950 to-violet-400/10 p-6 text-left"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div><span className="text-xs text-slate-500">SolHandle NFT</span><strong className="block text-3xl">@{handle}</strong></div><button onClick={() => navigator.clipboard.writeText(`@${handle}`)} className="rounded-lg border border-white/10 p-2 text-cyan-200" aria-label="Copy handle"><Copy className="h-4 w-4"/></button></div><dl className="mt-5 grid gap-5 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Owner wallet</dt><dd className="mt-1 font-mono text-slate-200">{shortenAddress(wallet)}</dd></div><div><dt className="text-slate-500">Network</dt><dd className="mt-1 text-slate-200">Solana Mainnet Beta</dd></div>{asset && <div className="sm:col-span-2"><dt className="text-slate-500">NFT asset</dt><dd className="mt-1 break-all font-mono text-slate-200">{asset}</dd></div>}</dl></div><p className="mt-6 flex items-center justify-center gap-2 text-sm text-slate-400"><ShieldCheck className="h-4 w-4 text-emerald-300"/>You own the NFT in your wallet. SolHandle never takes custody.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link to={`/${handle}`} className="inline-flex items-center justify-center gap-2 rounded-lg bg-gradient-to-r from-emerald-300 via-cyan-300 to-violet-400 px-5 py-3 font-semibold text-slate-950">View @{handle}<ArrowRight className="h-4 w-4"/></Link><Link to="/my-handles" className="rounded-lg border border-white/15 px-5 py-3 font-semibold text-white">Manage my handles</Link><a href={explorerUrl} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-lg border border-white/15 px-5 py-3 font-semibold text-white">View transaction<ExternalLink className="h-4 w-4"/></a></div><SimilarHandles handle={handle} title="You might also like"/></section></div></main>;
}