import { useState } from 'react';
import { Button } from '@/components/ui/button';
export default function GrowthAdminSeasonEditor({ season, onAction, busy }) {
  const [name, setName] = useState(season.name), [duration, setDuration] = useState(season.duration_days), [budget, setBudget] = useState(season.proposed_budget_tokens);
  return <article className="rounded-2xl border border-border bg-card p-6"><div className="flex flex-wrap justify-between gap-3"><h3 className="text-xl font-semibold">{season.name}</h3><span className="text-sm text-names-secondary">{season.status}</span></div>
    {season.status === 'DRAFT' && <form className="mt-5 grid gap-4 md:grid-cols-3" onSubmit={e => { e.preventDefault(); onAction({ action: 'save_season', id: season.id, name, duration_days: duration, proposed_budget_tokens: budget }); }}>
      <label className="text-sm">Naam<input required minLength={3} maxLength={100} value={name} onChange={e => setName(e.target.value)} className="mt-2 w-full rounded-lg border border-input bg-background px-3 py-2"/></label><label className="text-sm">Duur in dagen<input required type="number" min={1} max={90} step={1} value={duration} onChange={e => setDuration(e.target.value)} className="mt-2 w-full rounded-lg border border-input bg-background px-3 py-2"/></label><label className="text-sm">Voorgesteld $HANDLE-budget<input required inputMode="numeric" pattern="[0-9]{1,12}" value={budget} onChange={e => setBudget(e.target.value)} className="mt-2 w-full rounded-lg border border-input bg-background px-3 py-2"/></label><Button disabled={busy} className="md:col-span-3 md:justify-self-start">Concept opslaan</Button>
    </form>}
    <p className="mt-5 text-sm leading-7 text-muted-foreground">Een pilot starten activeert alleen season XP, geen tokens of treasurybetalingen. Budget en regels blijven na de start vastgezet.</p>{season.starts_at && <p className="mt-2 text-xs text-muted-foreground">{new Date(season.starts_at).toLocaleString('nl-NL')} – {new Date(season.ends_at).toLocaleString('nl-NL')}</p>}
    <div className="mt-5 flex flex-wrap gap-3">{['DRAFT', 'PAUSED'].includes(season.status) && <Button variant="outline" disabled={busy} onClick={() => { if (window.confirm('Start de XP-pilot? Dit activeert geen tokenrewards.')) onAction({ action: 'season_status', id: season.id, status: 'ACTIVE' }); }}>{season.status === 'DRAFT' ? 'Start XP-pilot' : 'Hervat XP-pilot'}</Button>}{season.status === 'ACTIVE' && <Button variant="outline" disabled={busy} onClick={() => onAction({ action: 'season_status', id: season.id, status: 'PAUSED' })}>Pauzeren</Button>}{['ACTIVE', 'PAUSED'].includes(season.status) && <Button variant="outline" disabled={busy} onClick={() => { if (window.confirm('Sluit dit seizoen af? Dit kan niet worden teruggedraaid.')) onAction({ action: 'season_status', id: season.id, status: 'ENDED' }); }}>Seizoen afsluiten</Button>}</div>
  </article>;
}