import { Link } from 'react-router-dom';
import { UserRound, Send, Box, Search, Wallet, Layers, Compass, ShoppingCart, Code2 } from 'lucide-react';
import HomeHandleTiles from '@/components/solhandle/home/HomeHandleTiles';
import HomeQuickExplanation from '@/components/solhandle/home/HomeQuickExplanation';

export default function HomeFunnelSections() {
  const benefits = [[UserRound, 'Simple identity', 'Replace a long wallet address with an @ name people can remember.'], [Send, 'Receive payments', 'Receive SOL through SolHandle Pay using your @ name.'], [Box, 'Yours on-chain', 'Your SolHandle is an NFT you own. No subscriptions. No renewals.']];
  const steps = [[Search, 'Search', 'Find the @ name you want.'], [Wallet, 'Connect', 'Connect your Solana wallet.'], [Box, 'Mint', 'Confirm the transaction and mint your SolHandle.'], [Layers, 'Use', 'Share your @, receive payments and use it as the ecosystem expands.']];
  return <>
    <section className="home-content-section lg:hidden"><h2 className="home-section-title">Why mint a SolHandle?</h2><div className="home-three-grid">{benefits.map(([Icon, title, text]) => <div key={title} className="home-info-card"><Icon className="h-10 w-10 shrink-0 text-names-accent"/><div><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-foreground/70">{text}</p></div></div>)}</div></section>
    <section className="home-content-section lg:hidden"><h2 className="home-section-title">Claim your @ in minutes</h2><div className="home-four-grid">{steps.map(([Icon, title, text], index) => <div key={title} className="home-info-card items-start"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-names-accent/15 text-sm font-bold text-names-accent">{index + 1}</span><div><Icon className="mb-3 h-6 w-6 text-names-secondary"/><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm text-foreground/70">{text}</p></div></div>)}</div></section>
    <HomeQuickExplanation/>
    <section className="home-content-section lg:hidden"><h2 className="home-section-title">Start exploring</h2><div className="home-four-grid">{[[Compass, 'Discover Names', 'Trending, available and for sale.', '/names'], [ShoppingCart, 'Marketplace', 'Buy and sell SolHandle names.', '/market'], [Layers, 'Integrations', 'Connect across Solana.', '/integrations'], [Code2, 'Developers', 'SDK, API and integration guides.', '/developers']].map(([Icon, title, text, path]) => <Link key={path} to={path} className="home-info-card"><Icon className="h-8 w-8 shrink-0 text-names-secondary"/><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-xs text-foreground/65">{text}</p></div><span className="ml-auto text-names-accent">→</span></Link>)}</div></section>
    <section className="home-content-section home-discover-section"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="home-section-title">Discover @ names</h2><Link to="/names" className="text-sm text-names-accent">Explore all handles →</Link></div><HomeHandleTiles/></section>
  </>;
}