import { Link } from 'react-router-dom';
import WeekendWinnerCards from '@/components/solhandle/weekend/WeekendWinnerCards';
export default function WeekendProofTable({ data }) {
  const exportCsv = () => {
    const csv = ['rank,wallet,handle,mint_signature,slot,transaction_index,minted_at,reward_HANDLE', ...data.winners.map(r => [r.rank,r.wallet,r.handle,r.signature,r.slot,r.transaction_index,r.minted_at,r.reward].join(','))].join('\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })), a = document.createElement('a'); a.href = url; a.download = 'solhandle-mint-weekend.csv'; a.click(); URL.revokeObjectURL(url);
  };
  return <section className="rounded-2xl border border-border bg-card p-4 lg:p-5"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-semibold">First 25 unique wallets</h2><button onClick={exportCsv} className="text-sm text-names-accent">Export wallet list (CSV)</button></div><p className="mt-2 text-sm text-muted-foreground">{data.scan?.final ? 'Final verified selection.' : 'Provisional selection until the weekend ends and the full chain scan completes.'}</p>{!data.winners.length ? <p className="py-8 text-muted-foreground">No qualifying mints verified yet.</p> : <><WeekendWinnerCards data={data}/><div className="mt-5 hidden overflow-x-auto lg:block"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border text-muted-foreground"><th className="p-3">Spot</th><th className="p-3">Original mint wallet</th><th className="p-3">Handle</th><th className="p-3">On-chain proof</th><th className="p-3">Reward</th></tr></thead><tbody>{data.winners.map(r => {
    const paid = data.settlements.find(s => s.key === `reward:${r.wallet}`);
    return <tr key={r.wallet} className="border-b border-border"><td className="p-3">#{r.rank}</td><td className="p-3"><a className="font-mono text-xs text-names-accent" href={`https://explorer.solana.com/address/${r.wallet}`} target="_blank" rel="noreferrer">{r.wallet}</a></td><td className="p-3"><Link to={`/${r.handle}`} className="text-names-accent">@{r.handle}</Link></td><td className="p-3"><a href={`https://explorer.solana.com/tx/${r.signature}`} target="_blank" rel="noreferrer" className="text-names-accent">Mint transaction ↗</a><span className="mt-1 block text-xs text-muted-foreground">Slot {r.slot} · tx #{r.transaction_index}<br/>{new Date(r.minted_at).toLocaleString('en-GB', { timeZone: 'Europe/Berlin' })} Berlin</span></td><td className="p-3 whitespace-nowrap">100,000 $HANDLE<br/>{paid ? <a href={`https://explorer.solana.com/tx/${paid.signature}`} target="_blank" rel="noreferrer" className="text-names-success">Paid ↗</a> : <span className="text-muted-foreground">{data.scan?.final ? 'Awaiting payout' : 'Provisional'}</span>}</td></tr>;
  })}</tbody></table></div></>}</section>;
}